### ISSUE TITLE
What is the logprobs in line 108 of the ShowTellModel?

### ISSUE THREAD

**Issue by eduOS** [ruotianluo/self-critical.pytorch#1]
Hi, @ruotianluo 
I got stuck in [this line](https://github.com/ruotianluo/self-critical.pytorch/blob/4db8d2016cb887d16a3654661ffffd5552b65e7e/misc/ShowTellModel.py#L108) since I cannot find it neither in `torch.autograd` nor the current file. 

Is it a typo or am I wrong? 

Best regards, 
Lerner

**Comment by ruotianluo** [comment]
It should be correct. What error did you get.

**Comment by eduOS** [comment]
You're right. It is defined at every step. The code checker alerts that something is wrong here since it is not defined ahead(maybe it is not allowed in python3). I am clear about this matter. Thanks for your reply.
