### ISSUE TITLE
Usage of GRU instead of an LSTM

### ISSUE THREAD

**Issue by rupeshS9102** [ruotianluo/self-critical.pytorch#101]
Hey @ruotianluo, thanks for your implementation!
I was wondering how the performance of the model would change, if a GRU was used instead of an LSTM. Have you tried it before. If you have any information on this, it would be very helpful.
Thanks!

**Comment by zhengyi123456** [comment]
I have once tried using GRU instead of LSTM, for simple soft attention model, the results seems equal.
