### ISSUE TITLE
Why we need shift the mask with one time step?

### ISSUE THREAD

**Issue by Beanocean** [ruotianluo/self-critical.pytorch#102]
Hello, Ruotian,

Thanks a lot for sharing the code.

I have one question about the mask used in calculating the [Self-Critical Loss](https://github.com/ruotianluo/self-critical.pytorch/blob/81186709358be84349343384166c6b177f7d8dec/misc/utils.py#L90). I think the ```sample_logprobs``` and the ```gen_results``` are aligned to each other, why the [code](https://github.com/ruotianluo/self-critical.pytorch/blob/81186709358be84349343384166c6b177f7d8dec/misc/utils.py#L94) shifts the mask one step afterward?

Any response will be appreciated.

**Comment by ruotianluo** [comment]
It's to include eos

**Comment by Beanocean** [comment]
> It's to include ```eos```

Thanks a lot for your reply, Ruotian. I think it is because the ```padding``` and ```eos``` use the same word index in your code, right?

**Comment by ruotianluo** [comment]
Yes
