### ISSUE TITLE
Confused about opt.num_layers

### ISSUE THREAD

**Issue by Cranooooooo** [ruotianluo/self-critical.pytorch#104]
Awesome code~

I got confused about the parameter of opt.num_layers. Does it mean the number of hidden layer in the LSTM cell or the number of LSTM used in the model?

(AttModel.py) According to the definition of init_hidden and line 455 and 462, opt.num_layers seems to stand for 2 LSTM(Language LSTM and Attention LSTM) used in the model.

**Comment by ruotianluo** [comment]
No worry, I almost never use it unless for transformee
