### ISSUE TITLE
Multi-GPU training error 

### ISSUE THREAD

**Issue by congve1** [ruotianluo/self-critical.pytorch#105]
Hi, ruotian
when I use self-critical training to train transformer model by multi-gpu(4-gpus). When coming to evaluation phase during training, I encounter the error as below:
```
Traceback (most recent call last):
  File "train.py", line 267, in <module>
    train(opt)
  File "train.py", line 215, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 120, in eval_split
    seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 62, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/public/home/G19940018/anaconda3/envs/yx1/lib/python2.7/site-packages/torch/nn/parallel/_functions.py", line 54, in forward
    assert all(map(lambda i: i.is_cuda, inputs))
```
Here is the bash  script I use to train:
```bash
id="transformer_rl"
ckpt_path="log_"$id
if [ ! -d $ckpt_path ]; then
  mkdir $ckpt_path
fi
if [ ! -f $ckpt_path"/infos_"$id$".pkl" ]; then
  start_from=""
else
  start_from="--start_from "$ckpt_path
fi

if [ x$1 != x ]; then
  GPU=$1
else
  GPU="0"
fi

export CUDA_VISIBLE_DEVICES=$GPU
python train.py --id $id --caption_model transformer --input_json data/cocotalk.json --input_label_h5 data/cocotalk_label.h5 --input_fc_dir data/cocobu_fc --input_att_dir data/cocobu_att --reduce_on_palteau --learning_rate 5e-5 --num_layers 6 --input_encoding_size 512 --rnn_size 2048 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 1000 --val_images_use 5000 --beam_size 3 --self_critical_after 29 --batch_size 80
unset CUDA_VISIBLE_DEVICES
```

My environment info:
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: CentOS Linux release 7.4.1708 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
CMake version: version 2.8.12.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB
GPU 2: Tesla P100-PCIE-16GB
GPU 3: Tesla P100-PCIE-16GB

Nvidia driver version: 410.72
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.14.5
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl    anaconda
[conda] cudatoolkit               10.0.130                      0    file:///public/home/G19940018/clw/conda_torch
[conda] mkl                       2018.0.3                      1    anaconda
[conda] mkl_fft                   1.0.1            py27h3010b51_0    anaconda
[conda] mkl_random                1.0.1            py27h629b387_0    anaconda
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.3.0           py27_cu10.0.130_1    file:///public/home/G19940018/clw/conda_torch
```

**Comment by ruotianluo** [comment]
Try replacing dp_model to model in l215 in train.py

**Comment by congve1** [comment]
@ruotianluo 
when change dp_model to model, it can do evaluation. But I met a problem.
```
Traceback (most recent call last):
  File "test_train.py", line 267, in <module>
    train(opt)
  File "test_train.py", line 215, in train
    model, lw_model.crit, loader, eval_kwargs)
  File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 160, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 55, in language_eval
    cocoEval.evaluate()
  File "coco-caption/pycocoevalcap/eval.py", line 59, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 44, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "coco-caption/pycocoevalcap/meteor/meteor.py", line 68, in _stat
    self.meteor_p.stdin.write(score_line+'\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128)
```
This is weird.
When I execute `eval.py`, this problem never happens

**Comment by ruotianluo** [comment]
That is weird. I don't have any thoughts.

**Comment by Wangt-CN** [comment]
> @ruotianluo
> when change dp_model to model, it can do evaluation. But I met a problem.
> 
> ```
> Traceback (most recent call last):
>   File "test_train.py", line 267, in <module>
>     train(opt)
>   File "test_train.py", line 215, in train
>     model, lw_model.crit, loader, eval_kwargs)
>   File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 160, in eval_split
>     lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
>   File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 55, in language_eval
>     cocoEval.evaluate()
>   File "coco-caption/pycocoevalcap/eval.py", line 59, in evaluate
>     score, scores = scorer.compute_score(gts, res)
>   File "coco-caption/pycocoevalcap/meteor/meteor.py", line 44, in compute_score
>     stat = self._stat(res[i][0], gts[i])
>   File "coco-caption/pycocoevalcap/meteor/meteor.py", line 68, in _stat
>     self.meteor_p.stdin.write(score_line+'\n')
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128)
> ```
> 
> This is weird.
> When I execute `eval.py`, this problem never happens

Hi, I have meet the same problem:
when evaluating during training on meteor: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128).
Have you got some idea? Thanks

**Comment by Wangt-CN** [comment]
> @ruotianluo 
> when change dp_model to model, it can do evaluation. But I met a problem.
> 
> ```
> Traceback (most recent call last):
>   File "test_train.py", line 267, in <module>
>     train(opt)
>   File "test_train.py", line 215, in train
>     model, lw_model.crit, loader, eval_kwargs)
>   File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 160, in eval_split
>     lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
>   File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 55, in language_eval
>     cocoEval.evaluate()
>   File "coco-caption/pycocoevalcap/eval.py", line 59, in evaluate
>     score, scores = scorer.compute_score(gts, res)
>   File "coco-caption/pycocoevalcap/meteor/meteor.py", line 44, in compute_score
>     stat = self._stat(res[i][0], gts[i])
>   File "coco-caption/pycocoevalcap/meteor/meteor.py", line 68, in _stat
>     self.meteor_p.stdin.write(score_line+'\n')
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128)
> ```
> 
> This is weird.
> When I execute `eval.py`, this problem never happens

@congve1 
Hi, I have meet the same problem:
when evaluating during training on meteor: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128).
Have you got some idea? Thanks

**Comment by congve1** [comment]
> > @ruotianluo
> > when change dp_model to model, it can do evaluation. But I met a problem.
> > ```
> > Traceback (most recent call last):
> >   File "test_train.py", line 267, in <module>
> >     train(opt)
> >   File "test_train.py", line 215, in train
> >     model, lw_model.crit, loader, eval_kwargs)
> >   File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 160, in eval_split
> >     lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
> >   File "/public/home/G19940018/clw/self-critical.pytorch/eval_utils.py", line 55, in language_eval
> >     cocoEval.evaluate()
> >   File "coco-caption/pycocoevalcap/eval.py", line 59, in evaluate
> >     score, scores = scorer.compute_score(gts, res)
> >   File "coco-caption/pycocoevalcap/meteor/meteor.py", line 44, in compute_score
> >     stat = self._stat(res[i][0], gts[i])
> >   File "coco-caption/pycocoevalcap/meteor/meteor.py", line 68, in _stat
> >     self.meteor_p.stdin.write(score_line+'\n')
> > UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128)
> > ```
> > 
> > 
> > This is weird.
> > When I execute `eval.py`, this problem never happens
> 
> @congve1
> Hi, I have meet the same problem:
> when evaluating during training on meteor: UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 57: ordinal not in range(128).
> Have you got some idea? Thanks

Well， I didn't fix this. Actually I just do not evaluate at training time.  I do the evaluation offline to judge which model is best.

**Comment by kangkang59812** [comment]
@congve1 
In `meteor.py`, try add these codes:
```
def enc(s):
    return s.encode('utf-8')


def dec(s):
    return s.decode('utf-8')
```

then replace all content in `meteor_p.stdin.write(eval_line + '\n')` `with meteor_p.stdin.write(enc(eval_line + '\n'))`
