### ISSUE TITLE
evaluation error using pre-trained model 

### ISSUE THREAD

**Issue by Jingzc** [ruotianluo/self-critical.pytorch#106]
when I try to run the following script:
python eval.py --model log_fc/model.pth --infos_path log_fc/infos_fc.pkl --image_folder blah --num_images 3
DataLoaderRaw loading images from folder:  blah
0
listing all images in directory blah
DataLoaderRaw found  3  images
Traceback (most recent call last):
  File "eval.py", line 76, in <module>
    vars(opt))
  File "/home/cjz/self-critical.pytorch-master/eval_utils.py", line 116, in eval_split
    tmp = [_.cuda() if _ is not None else _ for _ in tmp]
AttributeError: 'numpy.ndarray' object has no attribute 'cuda'

Thanks for any advice!

**Comment by luo3300612** [comment]
I add this before line 116 in eval_split.py then solve the problem
```python
tmp = [torch.from_numpy(_) if type(_) == np.ndarray else _ for _ in tmp]
```
