### ISSUE TITLE
some questions about prepro_ngrams

### ISSUE THREAD

**Issue by forence** [ruotianluo/self-critical.pytorch#107]
Hi Ruotian, 
1. I wanna to know why you add <EOS> to each sentence to calculate n_grams' frequency?
2. You use CiderD for calculating reward at self-critical phase and use standard Cider for evaluation, am I right?
Looking forward to your reply!

**Comment by ruotianluo** [comment]
1. Because cider score needs that.
2. Both are ciderd

**Comment by forence** [comment]
I'm missing \<EOS\> for the 1st question

**Comment by forence** [comment]
One more thing, which split should I use for calculating  n_grams' frequency? I noticed it is  'all' in your program, but also has a file named 'coco_val-idx.p'. Thanks a lot!

**Comment by ruotianluo** [comment]
Train split

**Comment by forence** [comment]
Both at self-critical training phase and evaluation phase are all using train split ?(I am more inclined to use train split when self-critical and train+test when evaluate the final score on paper, it not make sense to neglect test split when evaluation).
In other words, could you please give me some matchup for (1) Training(self-critical) (2)Validating (3)Testing
Thanks for your patience again!

**Comment by ruotianluo** [comment]
For evaluation, the ngrams are calculated on the fly on test images.

I computed ngrams in advance to make training more efficient.
