### ISSUE TITLE
image features with h5 extension.

### ISSUE THREAD

**Issue by mememimis** [ruotianluo/self-critical.pytorch#108]
Image features extracted with resnet as .h5 are not supported by dataloader?

I'm getting this error: IOError: [Errno 2] No such file or directory: 'data/cocotalk_fc/0.npy'

What i'm doing wrong?
thanks

**Comment by ruotianluo** [comment]
H5 is not supported in this repo.  Should be simple to be implemented through the hybridreader in dataloader.py. The reason h5 file is not supported because h5py has a bad support for parallel reading.

**Comment by mememimis** [comment]
Thank you very much. I noticed the tremendous gains in speed compared to the image captioning repo so i will keep it as such.
