### ISSUE TITLE
Paper for this implementation

### ISSUE THREAD

**Issue by arjung128** [ruotianluo/self-critical.pytorch#109]
Is there a paper for this implementation?

**Comment by ruotianluo** [comment]
No

**Comment by arjung128** [comment]
Why not? Are you working on writing one, or does the implementation not achieve state-of-the-art results?

**Comment by ruotianluo** [comment]
A paper means something new. There is not much new in this implementation. I do believe this is the best open source image captioning project in terms of performance.
