### ISSUE TITLE
cannot allocate memory

### ISSUE THREAD

**Issue by miracle24** [ruotianluo/self-critical.pytorch#11]
When I run the att2in2 model with cross entropy loss, I got 'cannot allocate memory' error. I don't know why. The detail is: 
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start            
    self._popen = Popen(self)                                                       
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__       
    self.pid = os.fork()                                                              
OSError: [Errno 12] Cannot allocate memory 

because of my fault, I cannot get all the details. But I known it comes from the detaloader.py which loads the data with multiprocess. It seems that the error didn't happen regularly. Sometimes the whole training  can be over without errors, sometimes not. Have you ever met this error? @ruotianluo

**Comment by ruotianluo** [comment]
It happens to me sometime too, but varies from machine to machine. https://github.com/pytorch/pytorch/issues/1355
I guess it's related to the setting of different machine.

**Comment by miracle24** [comment]
Thanks a lot. Zan yi ge!
