### ISSUE TITLE
cocobu_box for visual genome

### ISSUE THREAD

**Issue by arjung128** [ruotianluo/self-critical.pytorch#111]
First of all, thank you for making your work public. It has really been very helpful. 

I am trying to use this implementation (specifically the transformer model) on the visual genome dataset -- I was able to find the `cocobu_att` and `cocobu_fc` equivalents, but not the equivalent of `cocobu_box`. How was `cocobu_box` generated? 

Can the transformer model work without `cocobu_box`, or does it require it? Can the equivalent for the visual genome dataset be found anywhere?

**Comment by ruotianluo** [comment]
cocobu_box is something I tried and doesn't seem to work much. Since bottom up is generated from each detected bounding boxes, cocobu_box is basically the coordinates of each boxes.

transformer works without cocobu_box.

there is currently no VG.
