### ISSUE TITLE
structure of the transformer captioning

### ISSUE THREAD

**Issue by YuansongFeng** [ruotianluo/self-critical.pytorch#112]
I am curious about the details regarding how you are integrating transformer into the captioning framework. The way that I understand it now, the whole picture works as follows:

1. for each image, use resent to extract features in C x W x H format, where C is usually 512 and W and H are 7. 
2. each one of the spatial feature (C x 1 x 1) becomes one input to the decoder dec_enc_att module,  so that there are a total of W\*H inputs to the dec_enc_att. As an analogy, each one of the inputs is like a single word embedding in a text-to-text translation task, and there are W\*H 'words' from each image. 
3. Each spatial feature (C x 1 x 1) undergoes a linear transformation before being inputted to the dec_enc_att module. The dec_enc_att module treats these W\*H projected spatial feature as both Keys and Values (as defined in the transformer structure), and uses the outputs as the Queries. 

Is the understanding above correct? If not, would you kindly point me out any misunderstanding? Thanks @ruotianluo !

**Comment by ruotianluo** [comment]
I am not sure if you said about 3 is correct. But I think your bullet point 2 is essentially my implementation.

**Comment by Shiv681991** [comment]
Hi @ruotianluo , Thanks for the repository. I was wondering if it would be possible for you to maybe add a simple schematic of the transformer based captioning implemented. As it will surely be a lot helpful for overall understanding. Thanks.
