### ISSUE TITLE
Usage of requires_grad

### ISSUE THREAD

**Issue by Silenthinker** [ruotianluo/self-critical.pytorch#12]
Hi,

In the `sample` method of  `ShowTellModel.py`, `requires_grad` is set to `False` (line 148 and 151). I am wondering why we need to do so. Is it related to differentiation in the presence of the stochastic node `torch.multinomial` in line 147? Thanks.

**Comment by ruotianluo** [comment]
No, that's not necessary. A variable created from a tensor is defaultly requries_grad False.
