### ISSUE TITLE
No such file or directory: 'coco-caption/f30k_captions4eval.json'

### ISSUE THREAD

**Issue by SmallSmallQiu** [ruotianluo/self-critical.pytorch#122]
当我使用f30k数据集进行训练时，到了检测阶段提示这个文件没有，我在GitHub上也没有找到相关的文件，请问这个文件是要自己生成还是在哪里找到？

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/self-critical.pytorch/tree/master/data
在这里有。
