### ISSUE TITLE
Running time too long for 30 epochs

### ISSUE THREAD

**Issue by chengxili** [ruotianluo/self-critical.pytorch#126]
--id topdown 
--caption_model topdown 
--batch_size 100 
--learning_rate 5e-4 
--learning_rate_decay_start 0 
--scheduled_sampling_start 0 
--checkpoint_path log_test3_cuda 
--save_checkpoint_every 10000 
--val_images_use 5000 
--max_epochs 30 
--rnn_size 1000 
--input_encoding_size 1000 
--att_feat_size 2048 -
-att_hid_size 512 
--self_critical_after 20
Hi, ruotian!
I run 180000 data with this setting and cost about 30 hours to run 30 epochs, is it normal? I had two GPUS with 11G gpu RAM

**Comment by zhengyi123456** [comment]
It is normal. The MSCOCO dataset is not small and training LSTM network costs time.

**Comment by chengxili** [comment]
Thanks, Ruotian!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yi Zheng(郑逸)"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月26日(星期二) 下午5:05
收件人:&nbsp;"ruotianluo/self-critical.pytorch"<self-critical.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"sissy"<281256221@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ruotianluo/self-critical.pytorch] Running time too long for 30 epochs (#126)




It is normal. The MSCOCO dataset is not small and training LSTM network costs time.

**Comment by chengxili** [comment]
> It is normal. The MSCOCO dataset is not small and training LSTM network costs time.
Thanks! Going to close this
