### ISSUE TITLE
using beam size is set to 1 by default during evaluation?

### ISSUE THREAD

**Issue by fawazsammani** [ruotianluo/self-critical.pytorch#127]
Hi. Thanks for your code!
I'd like to ask regarding the following part of your code in `eval_utils.py`:
```
        with torch.no_grad():
            seq = model(fc_feats, att_feats, att_masks, opt=eval_kwargs, mode='sample')[0].data
        
        # Print beam search
        if beam_size > 1 and verbose_beam:
            for i in range(loader.batch_size):
                print('\n'.join([utils.decode_sequence(loader.get_vocab(), _['seq'].unsqueeze(0))[0] for _ in model.done_beams[i]]))
                print('--' * 10)
        sents = utils.decode_sequence(loader.get_vocab(), seq)
```
It seems that by default your calling the `_sample` model for generating the `sents`, and evaluation is done on it only, since the part inside the beam size is just for printing. Is that true? Or did I miss something else in the code?

**Comment by ruotianluo** [comment]
beam size would be in eval_kwargs, and sample would parse it and use sample_beam when beam_size > 1

**Comment by fawazsammani** [comment]
Thank you! Sorry that i missed that
