### ISSUE TITLE
Why newfc extend AttModel?

### ISSUE THREAD

**Issue by luo3300612** [ruotianluo/self-critical.pytorch#128]
Thank you for your repo, Here is my question
when I eval newfc, there is some error
```shell
tmp_att_feats = p_att_feats[k:k+1].expand(*((beam_size,)+p_att_feats.size()[1:])).contiguous()
TypeError: 'NoneType' object has no attribute '__getitem__'
```
and I found that newfc extends AttModel, but in initialization, we do not read att feats for newfc as in misc.utils.py
```python
def if_use_feat(caption_model):
    # Decide if load attention feature according to caption model
    if caption_model in ['show_tell', 'all_img', 'fc', 'newfc']:
        use_att, use_fc = False, True
    elif caption_model == 'language_model':
        use_att, use_fc = False, False
    elif caption_model in ['topdown', 'adaatt','stackatt','denseatt','adaattmo']:
        use_fc, use_att = True, True
    else:
        use_att, use_fc = True, False
    return use_fc, use_att
```
So could you please tell me why newfc extend AttModel ?

**Comment by ruotianluo** [comment]
replace l770 in AttModel.py with         return fc_feats, att_feats, att_feats, att_masks.

I fixed it locally.

**Comment by luo3300612** [comment]
> replace l770 in AttModel.py with return fc_feats, att_feats, att_feats, att_masks.
> 
> I fixed it locally.

Thanks for your reply. It works.
Actually I am more interested in why it extends AttModel than solving this problem.
I will appreciate it if you could tell me ~

**Comment by ruotianluo** [comment]
Basically treat fc model as a special case of attmodel where there is no attention.

So that the fc model can reuse all the functions of attmodel. Basically to reduce redundant code.

**Comment by andrewcao95** [comment]
> Basically treat fc model as a special case of attmodel where there is no attention.
> 
> So that the fc model can reuse all the functions of attmodel. Basically to reduce redundant code.


You mean the newfc is like show tell and attmodel like show attend tell?  I want to train show tell and show attend tell model as experiment result compare. Any suggestions?

#53

**Comment by ruotianluo** [comment]
FC is what's in self. Critical sequence training paper. It's not exactly show and tell but quite similar. Same for att2in which can be viewed as a variant for show attend and tell

**Comment by andrewcao95** [comment]
> FC is what's in self. Critical sequence training paper. It's not exactly show and tell but quite similar. Same for att2in which can be viewed as a variant for show attend and tell

Got it. That‘s different and will be treat as different compare methods. So, how to run train the original show tell and show attend tell ? (I think it ’s important as a baseline to compare.)

**Comment by ruotianluo** [comment]
If you really want to compare, you can try running it and fix all the errors.
