### ISSUE TITLE
About the adaptive attention model.

### ISSUE THREAD

**Issue by miracle24** [ruotianluo/self-critical.pytorch#13]
Does your code can replicate the adaptive attention model. I run your code with max_epoch 30 and the default settings in opts.py. But I did not obtain that high cider in the adaptive attention paper. If you did replicate the result in the paper, I'll appreciate if you tell me the experiment settings in detail. Thank you!

**Comment by ruotianluo** [comment]
No, I didn't spend time to replicate the result.

**Comment by ruotianluo** [comment]
No, I didn't spend time on replicating the result. I did remember I got worse result than in the paper.

**Comment by miracle24** [comment]
Thanks!

**Comment by jiasenlu** [comment]
In order to get the similar number, I find finetuning the CNN is very important. This code use pre-extracted feature, so the number should be lower as reported in the paper.

**Comment by yueranjzx** [comment]
I noticed that the adaptive attetion model use a fixed att_size 14, is that an optimal choice or just a empirical one?
