### ISSUE TITLE
AttentionEnsmeble

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#130]
Hi. Thanks for your work!
May I know what is meant by AttentionEnsemble in your code? What exactly is getting evaluated as an ensemble? Is it the same model trained with different initialisation techniques?

**Comment by ruotianluo** [comment]
It's a test only model. You can train several models separately, and ensemble them at test time. Ensemble means averaging the word predictions from different models at each time step.
