### ISSUE TITLE
Couldn't find coco-train-idxs.p while self-critical training.

### ISSUE THREAD

**Issue by JincanDeng** [ruotianluo/self-critical.pytorch#131]
Thanks for your great work! It helps me a lot.
When I try to train a transformer model with self-critical training, the error that coco-train-idxs.p cannot be found occurs.

**Comment by ruotianluo** [comment]
Run
python scripts/prepro_ngrams.py --input_json .../dataset_coco.json --dict_json data/cocotalk.json --output_pkl data/coco-train --split train
