### ISSUE TITLE
question regarding CiderD_scorer.compute_score

### ISSUE THREAD

**Issue by fawazsammani** [ruotianluo/self-critical.pytorch#132]
Hello Ruotian,
Thanks for your great code. 
I have a question regarding computing the cider score when training with self-critical. Actually, in my code for the ground-truth captions, I am constantly using 5 captions per image. So in my `data['gts']`, each element in the list is a numpy matrix of shape `(5, max_len)`.  Therefore, in this line here: 
`gts = {i: gts[i % batch_size // seq_per_img] for i in range(2 * batch_size)}`
For each image, we would have a duplicate number of ground truth captions if 5 captions are originally not present in the karpathy split. For example, rathen than having:

```
{image 1 : [c1, c2, c3], 
image 2: [c1, c2, c3, c4], 
image 3: [c1, c2, c3, c4, c5]}
```

I would have a constant number of 5 captions for each image:

```
{image 1 : [c1, c2, c3, c4, c5], 
image 2: [c1, c2, c3, c4, c5], 
image 3: [c1, c2, c3, c4, c5]}

```
So does these duplicate captions affect the cider score (example: induce it to be higher)? Does the cider code passes the ground truth captions through a `set` to filter duplicate captions? 
Thanks!

**Comment by ruotianluo** [comment]
It's very rare in coco, so I think it's not a big beal.

**Comment by fawazsammani** [comment]
Alright, Thanks!
