### ISSUE TITLE
How about the transformer results?

### ISSUE THREAD

**Issue by Cathyttt** [ruotianluo/self-critical.pytorch#141]
Hello, thank you for your code but I was wondering about the results from the transformer model. Because I get bad results on bleu. And I can't find your transformer benchmarks. Can someone tell me 
the transformer's performance? And what's your appropriate value of parameters for training?

**Comment by ruotianluo** [comment]
python train.py --id $id --caption_model transformer --noamopt --noamopt_warmup 20000 --label_smoothing 0.0 --input_json data/cocotalk.json --input_label_h5 data/cocotalk_label.h5 --input_fc_dir data/cocobu_fc --input_att_dir data/cocobu_att --seq_per_img 5 --batch_size 10 --beam_size 1 --learning_rate 5e-4 --num_layers 6 --input_encoding_size 512 --rnn_size 2048 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use 5000 --max_epochs 15

python train.py --id $id --caption_model transformer --reduce_on_plateau --input_json data/cocotalk.json --input_label_h5 data/cocotalk_label.h5 --input_fc_dir data/cocobu_fc --input_att_dir data/cocobu_att --input_box_dir data/cocobu_box --seq_per_img 5 --batch_size 10 --beam_size 1 --learning_rate 1e-5 --num_layers 6 --input_encoding_size 512 --rnn_size 2048 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use 5000 --self_critical_after 10

This gives me 1.25 cider score. Not sure on Bleu.

**Comment by fawazsammani** [comment]
@ruotianluo 1.25 is after cider optimization right? Do you remember the score for XE when using Transformers?

**Comment by ruotianluo** [comment]
Around 1.12 without beam search on val.
