### ISSUE TITLE
Is the reward computed at the end of caption and with respect to all possible ground-truth caption?

### ISSUE THREAD

**Issue by ehsan-soe** [ruotianluo/self-critical.pytorch#143]
Hi I am trying to understand the idea of self-critical RL to implement it for my own usecase. In this regard I am confused about:

1) Shouldn't the reward be computed at the end of caption (for full sequence) ? if yes, would you please let me know the shape of the computed reward [here](https://github.com/ruotianluo/self-critical.pytorch/blob/9b36d9bf1cad47cd8c917c895d926b3ff3d3e5e8/misc/rewards.py#L72). Since it should match the dimension of [input](https://github.com/ruotianluo/self-critical.pytorch/blob/9b36d9bf1cad47cd8c917c895d926b3ff3d3e5e8/misc/utils.py#L95) which is [batch_size, sequence_length] before flattening.

Thanks in advance
2) is the reward computed with respect to all possible ground-truth?

**Comment by ruotianluo** [comment]
1. yes. yes, you are correct.
2. yes

**Comment by ehsan-soe** [comment]
@ruotianluo Thanks you so much.
Just one more question is [this mask ](https://github.com/ruotianluo/self-critical.pytorch/blob/9b36d9bf1cad47cd8c917c895d926b3ff3d3e5e8/misc/utils.py#L93) for <unk> or <pad> tokens being predicted by the model?

**Comment by ruotianluo** [comment]
only pad.
