### ISSUE TITLE
scheduled sampling in transformer

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#146]
Hi @ruotianluo . I have a question about using the scheduled sampling in the Transformer Model.
In the transformer, you are overriding the forward function of the AttModel with:
```
    def _forward(self, fc_feats, att_feats, seq, att_masks=None):
        att_feats, seq, att_masks, seq_mask = self._prepare_feature_forward(att_feats, att_masks, seq)

        out = self.model(att_feats, seq, att_masks, seq_mask)

        outputs = self.model.generator(out)
        return outputs
```
So there is actually no scheduled sampling here. How does your code use the scheduled sampling in that case of the transformer if it is not available in the forward function?

**Comment by ruotianluo** [comment]
It's not using scheduled sampling. Basically scheduled sampling is ignored.

**Comment by homelifes** [comment]
Thanks! Because according to issue #141 , scheduled sampling is included.
Appreciate your reply.
