### ISSUE TITLE
label smoothing question

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#149]
Hi @ruotianluo . Thanks for your code. 

I was wondering wethear it is needed to take the negative of the logprobs when performing Label Smoothing Loss, as you did in XE:
`output = -input.gather(2, target.unsqueeze(2)).squeeze(2) * mask`
In Label Smoothing, do we need to take -logprobs or logprobs?

**Comment by homelifes** [comment]
@ruotianluo

**Comment by ruotianluo** [comment]
logprobs I think
