### ISSUE TITLE
cocotest_bu_att and cocotest_bu_fc

### ISSUE THREAD

**Issue by tong8080** [ruotianluo/self-critical.pytorch#155]
Hello, I didn't find the cocotest_bu_att and cocotest_bu_fc file in your google drive link. I only find cocobu_att and cocobbu_fc.

**Comment by ruotianluo** [comment]
https://drive.google.com/open?id=1eCdz62FAVCGogOuNhy87Nmlo5_I0sH2J

I uploaded it.

**Comment by tong8080** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruotian(RT) Luo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 凌晨2:17
收件人:&nbsp;"ruotianluo/self-critical.pytorch"<self-critical.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"一洛"<2464837202@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ruotianluo/self-critical.pytorch] cocotest_bu_att and cocotest_bu_fc (#155)




https://drive.google.com/open?id=1eCdz62FAVCGogOuNhy87Nmlo5_I0sH2J
 
I uploaded it.
