### ISSUE TITLE
The pretrained FC model has bad performance

### ISSUE THREAD

**Issue by cshanjiewu** [ruotianluo/self-critical.pytorch#156]

**Comment by cshanjiewu** [comment]
thanks for your good works, but the performance of pretrained fc model is so bad, the evaluation metrics is almost zero.
https://drive.google.com/drive/folders/1AG8Tulna7gan6OgmYul0QhxONDBGcdun

**Comment by ruotianluo** [comment]
Did you pull from the master?

**Comment by cshanjiewu** [comment]
YES, I just pull the newest version. I just find that when I test the raw images by eval.py, the result is good. But, when I test on Karpathy's test split, the result is bad. I test on another pretrained model like topdown and it is fine. So I think the data of prepro-feature is good and the fc model is good. But testing on Karpathy's test split by fc model is bad, I just don't know where is wrong?

**Comment by ruotianluo** [comment]
Can you download the cocotalk.json and cocotalk_label.h5 from https://drive.google.com/open?id=1eCdz62FAVCGogOuNhy87Nmlo5_I0sH2J

**Comment by ruotianluo** [comment]
Sorry, I forgot to push a bug fix.

**Comment by cshanjiewu** [comment]
It works. Thank you so much!

**Comment by cshanjiewu** [comment]
By the way, When loading fc_rl pretrained model. It will output this error:
`RuntimeError: Error(s) in loading state_dict for NewFCModel:
	Missing key(s) in state_dict: "fc_embed.bias", "fc_embed.weight", "_core.i2h.bias", "_core.i2h.weight", "_core.h2h.bias", "_core.h2h.weight". 
	Unexpected key(s) in state_dict: "ctx2att.weight", "ctx2att.bias", "core.a2c.weight", "core.a2c.bias", "core.i2h.weight", "core.i2h.bias", "core.h2h.weight", "core.h2h.bias", "core.h2att.weight", "core.h2att.bias", "core.alpha_net.weight", "core.alpha_net.bias". `
