### ISSUE TITLE
Evaluate BUTD on Raw Images

### ISSUE THREAD

**Issue by windweller** [ruotianluo/self-critical.pytorch#157]
Hi Ruotian,

This repo is amazing :) I was working on Pythia for the past couple of days and that codebase was horrible ("too modular" turns out to be a sin!). However, there is one thing that they do I think is interesting, they provided a demo to generate BUTD features from Fast-RCNN in Python (so you can evaluate on any raw image). 

Here's [Pythia](https://github.com/facebookresearch/pythia) and link to [CoLab demo](https://colab.research.google.com/drive/1vzrxDYB0vxtuUy8KCaGxm--nDCJvyBSg). 

If I run their code:

```python
from maskrcnn_benchmark.config import cfg
from maskrcnn_benchmark.layers import nms
from maskrcnn_benchmark.modeling.detector import build_detection_model
from maskrcnn_benchmark.structures.image_list import to_image_list
from maskrcnn_benchmark.utils.model_serialization import load_state_dict

  def _build_detection_model(self):

      cfg.merge_from_file('/content/model_data/detectron_model.yaml')
      cfg.freeze()

      model = build_detection_model(cfg)
      checkpoint = torch.load('/content/model_data/detectron_model.pth', 
                              map_location=torch.device("cpu"))

      load_state_dict(model, checkpoint.pop("model"))

      model.to("cuda")
      model.eval()
      return model

  def get_detectron_features(self, image_path):
      im, im_scale = self._image_transform(image_path)
      img_tensor, im_scales = [im], [im_scale]
      current_img_list = to_image_list(img_tensor, size_divisible=32)
      current_img_list = current_img_list.to('cuda')
      with torch.no_grad():
          output = self.detection_model(current_img_list)
      feat_list = self._process_feature_extraction(output, im_scales, 
                                                  'fc6', 0.2)
      return feat_list[0]
```

For every new image, the returned feature vector has shape of `torch.Size([100, 2048])` (for 1 image). My question here is: Is this a viable solution to add BUTD feature preprocessing to your pipeline? Does the 100 correspond to the "fixed" or "adaptive" feature size you talk about in [data](https://github.com/ruotianluo/self-critical.pytorch/tree/master/data)?

Since I'm still very new to your library, does it matter if I use fixed or adaptive feature size?

**Comment by ruotianluo** [comment]
Thank you for bringing me this. I didn't know pythia has this.

Fixed and adaptive were used in original BUTP paper. Fixed was 30 detections and adaptive is 10-100 detection. It's first thresholded by a confidence threshold(0.2), if the remaining boxes are greater than 100 or less than 10, they just take top10/top100 detection.

**Comment by ruotianluo** [comment]
I do have raw image evaluation available in https://github.com/ruotianluo/GoogleConceptualCaptioning. If you download the docker image, that includes a runnable build of caffe in that docker to extract the features.

**Comment by windweller** [comment]
Ah, I see...so essentially what Pythia's code did was that they used all 100 features without thresholding. 

Does the fixed vs. adaptive make a difference in performance? I'm downloading the pre-computed features right now.

Thanks for the docker pointer, will check it out :)

**Comment by ruotianluo** [comment]
I think adaptive is better than fixed by only a little. But I don't have any proof.

**Comment by windweller** [comment]
Ahh, gotcha :) Thanks!
