### ISSUE TITLE
Evaluating Pre-trained Model Has Bad Result

### ISSUE THREAD

**Issue by windweller** [ruotianluo/self-critical.pytorch#158]
I downloaded the pretrained models from Google Drive:

```bash
ls ./data/bottomup/trans_nsc
infos_trans_nsc-best.pkl  model-best.pth  trans_nsc_test.json
```

I also downloaded the peteanderson80's original file (with "adaptive" features). After downloading these zipped files, I unzipped them according to instruction and run `python script/make_bu_data.py --output_dir data/cocobu`.

My data folder looks like:
```bash
ls ./data/
bottomup                           bu_data     cocobu_box  cocotalk.json      dataset_coco.json       dataset_flickr8k.json  README.md
bottomup-20200119T025147Z-001.zip  cocobu_att  cocobu_fc   cocotalk_label.h5  dataset_flickr30k.json  mscoco
```

Then I used the following command to evaluate:

```bash
python3.6 eval.py --dump_images 0 --num_images 5000 --model ./data/bottomup/trans_nsc/model-best.pth --infos_path ./data/bottomup/trans_nsc/infos_trans_nsc-best.pkl --language_eval 1 --sample_method bs --beam_size 5
```

But the captions printed out are gibberish...
```
image 192440: wipe shamrock doing wipe bratwurst payer wipe aggressive payer wipe preparing
image 1146: wipe sheriff supposed commode payer wipe cactus payer vietnamese
image 559665: tucks giant undergoing outdoor wipe toting outdoor wipe baseline
image 394240: wipe hull rubs cage grounds outdoor texting address rubs wipe mates
image 491497: wipe cellar poster doing wipe afraid sparse payer wipe nokia
image 184791: wipe eva doing wipe piercings rubs wipe framing payer wipe slats
```

Something must have gone wrong...

Can someone let me know why?

I guess I can also train a model from scratch using the instructions and maybe this problem will be mitigated.

**Comment by ruotianluo** [comment]
I just pushed a fix yesterday.

**Comment by windweller** [comment]
Ahh that fixed everything :)

I guess I pulled your repo a bit too early...cool and thanks!
