### ISSUE TITLE
Init cider scorer at every epoch?

### ISSUE THREAD

**Issue by gonnafree** [ruotianluo/self-critical.pytorch#16]
I saw that you call the `init_cider_scorer()` function at every epoch when doing self-critical training.  It can slow down the training time a little bit. Why don't you just call it somewhere outside the training loop?

**Comment by ruotianluo** [comment]
You are right. I will change the init cider scorer

**Comment by ruotianluo** [comment]
Should be fixed by https://github.com/ruotianluo/self-critical.pytorch/commit/fd445dc935e1a474150107faa4c36be81415892d
