### ISSUE TITLE
features from google drive broken?

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#163]
Hi. I downloaded the cocobu_att and cocobu_fc features from your google drive. When I unzipped the tar file, i found a single file with 24G (for att) and 1G (for fc) with no extension. However, the code is expecting individual .npy files for loading the features (>123K individual files). So How can i extract these files from the single file extracted from that tar zip in your google drive?
![Capture](https://user-images.githubusercontent.com/46392773/73930933-5f941280-4912-11ea-84bb-cde40b9762a5.PNG)

**Comment by ruotianluo** [comment]
Should be just like a normal tar, nothing special

**Comment by homelifes** [comment]
Hi,
I don’t understand. The of extracted file from the tar has no extension, and I cannot unzip it. I can only unzip the tar file. Once I unzip the tar file, this big file in the image is only there which cannot be unzipped. Kindly help because I’m using windows so I cannot run the make_bu_data.py that you provided.

**Comment by ruotianluo** [comment]
Can you untar it again. 
```
mkdir cocobu_fc
cd cocobu_fc
tar -xvf ../cocobu_fc.tar
```

I found no problem

**Comment by homelifes** [comment]
Yes it works with the command. Thanks
