### ISSUE TITLE
data loader for running on windows

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#165]
Hi,
It seems that the libraries used in dataloader.py dont work on windows, only on Linux. I tried it on my personal PC with Linux and it works, but my office PC is windows. So I get the error below. According to the issue [here](https://github.com/husthuaan/AoANet/issues/5#issuecomment-533894304) this fixes the problem. But ive seen you changed in dataloader.py. So if i use the old dataloader code which is the windows-equivalent to the link I attached, would there be any problem for the other parts of the code?

>  File "<string>", line 1, in <module>
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\USER\Anaconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\USER\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\USER\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\USER\Desktop\self-critical\train.py", line 277, in <module>
>     train(opt)
>   File "C:\Users\USER\Desktop\self-critical\train.py", line 37, in train
>     loader = DataLoader(opt)
>   File "C:\Users\USER\Desktop\self-critical\dataloader.py", line 294, in __init__
>     self.iters[split] = iter(self.loaders[split])
>   File "C:\Users\USER\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
> Traceback (most recent call last):
>   File "C:\Users\USER\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
>   File "train.py", line 277, in <module>
>         w.start()train(opt)
> 
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\process.py", line 112, in start
>   File "train.py", line 37, in train
>     loader = DataLoader(opt)
>   File "C:\Users\USER\Desktop\self-critical\dataloader.py", line 294, in __init__
>     self.iters[split] = iter(self.loaders[split])
>   File "C:\Users\USER\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
>     return _MultiProcessingDataLoaderIter(self)
>   File "C:\Users\USER\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
>         w.start()
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\process.py", line 112, in start
> self._popen = self._Popen(self)
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
>     self._popen = self._Popen(self)
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
>         return _default_context.get_context().Process._Popen(process_obj)return _default_context.get_context().Process._Popen(process_obj)
> 
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
>     return Popen(process_obj)
> return Popen(process_obj)  File "C:\Users\USER\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
> 
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
>     prep_data = spawn.get_preparation_data(process_obj._name)
> reduction.dump(process_obj, to_child)  File "C:\Users\USER\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
> 
>       File "C:\Users\USER\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
> _check_not_importing_main()
>   File "C:\Users\USER\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
>     is not going to be frozen to produce an executable.''')
> RuntimeError:
>         An attempt has been made to start a new process before the
>         current process has finished its bootstrapping phase.
> 
>         This probably means that you are not using fork to start your
>         child processes and you have forgotten to use the proper idiom
>         in the main module:
> 
>             if __name__ == '__main__':
>                 freeze_support()
>                 ...
> 
>         The "freeze_support()" line can be omitted if the program
>         is not going to be frozen to produce an executable.
>     ForkingPickler(file, protocol).dump(obj)
> BrokenPipeError: [Errno 32] Broken pipe

**Comment by mememimis** [comment]
I encountered a similar issue and in order to keep the previous dataloader i followed the commits  and i made the respective changes. It is not much work and it works fine.

**Comment by ruotianluo** [comment]
I did something else in the dataloader before using pytorch dataloader. You can try to apply the modification on the dataloder in the commit before the change

**Comment by homelifes** [comment]
Thanks. Its working. Additionally, the input and labels need to be of type Long (although they already are). I did this by x.long() and targets.long(). I'm using PyTorch 1.2
