### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by andrewcao95** [ruotianluo/self-critical.pytorch#168]
ZeroDivisionError: division by zero
Hi Dr. Luo. I try to evaluate model, but I meet an error.

error info:
```shell
python eval.py --model data/pretrain/fc/model-best.pth  --infos_path data/pretrain/fc/infos_fc-best.pkl --image_folder blah --num_images -1
loading annotations into memory...
0:00:00.498650
creating index...
index created!
Traceback (most recent call last):
  File "eval.py", line 71, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "/home/andrewcao95/workspace/pycharm_ws/self-critical.pytorch/eval_utils.py", line 83, in language_eval
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

```

source code:
```shell
# filter results to only those in MSCOCO validation set
    preds_filt = [p for p in preds if p['image_id'] in valids]
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
    mean_entropy = sum([_['entropy'] for _ in preds_filt]) / len(preds_filt)
    print('using %d/%d predictions' % (len(preds_filt), len(preds)))
    json.dump(preds_filt, open(cache_path, 'w')) # serialize to temporary json file. Sigh, COCO API...

    cocoRes = coco.loadRes(cache_path)
    cocoEval = COCOEvalCap(coco, cocoRes)
    cocoEval.params['image_id'] = cocoRes.getImgIds()
    cocoEval.evaluate()

    for metric, score in cocoEval.eval.items():
        out[metric] = score
    # Add mean perplexity
    out['perplexity'] = mean_perplexity
    out['entropy'] = mean_entropy

    imgToEval = cocoEval.imgToEval
    for k in list(imgToEval.values())[0]['SPICE'].keys():
        if k != 'All':
            out['SPICE_'+k] = np.array([v['SPICE'][k]['f'] for v in imgToEval.values()])
            out['SPICE_'+k] = (out['SPICE_'+k][out['SPICE_'+k]==out['SPICE_'+k]]).mean()
    for p in preds_filt:
        image_id, caption = p['image_id'], p['caption']
        imgToEval[image_id]['caption'] = caption
```

**Comment by ruotianluo** [comment]
It looks like len(preds_filt) == 0

**Comment by andrewcao95** [comment]
> It looks like len(preds_filt) == 0

Yes. The len(preds_filt) is show 0, that's why error occur. Actually, I try to use your previous work Image_Captioning_AI_Challenger to train a Chinese image captioning model. But I notice the previous work have some bugs. So I try to do that base the self-critical.pytorch.

Step1. I use  Image_Captioning_AI_Challenger 's dataset preprocessing code to generate coco type json file.

Step2. I use those dataset files to train a model on  self-critical.pytorch base on bottom up pre extract feature. The training process is good. But when I try to evaluate the model by Karpathy's test split. The ZeroDivisionError: division by zero error occur. I try to debug where going wrong, in this part
```
preds_filt = [p for p in preds if p['image_id'] in valids]
mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
```
`p['image_id']` is filename like ***.jpg while `valids` is hash id type. So the two value is not match. That why preds_filt == 0.

I find in Image_Captioning_AI_Challenger, you do `img['image_id'] = int(int(hashlib.sha256(img['image_id']).hexdigest(), 16) % sys.maxint)` in prepro_reference_json.py (Image_Captioning_AI_Challenger) to generate id.

And in Image_Captioning_AI_Challenger 's prepro_labels.py
```
    if 'filename' in img: jimg['file_path'] = os.path.join(img['filepath'], img['filename']) # copy it over, might need
    if 'cocoid' in img: jimg['id'] = img['cocoid'] # copy over & mantain an id, if present (e.g. coco ids, useful)
```
you dump the filename into id and save as chinese_talk.json and .h5.

I can not figure out where is wrong？

**Comment by ruotianluo** [comment]
pred_filt is the filtered preds. All the preds that image_id not in coco validation set will be removed. To use the chinese_talk, you use the official evaluation code, and processed validation set.

https://github.com/ruotianluo/Image_Captioning_AI_Challenger/blob/master/eval_utils.py#L21

**Comment by andrewcao95** [comment]
Hi Dr. Luo, Thanks for your quick reply. Follow your advice, I git clone bellow work into project root path and rename as AI_Challenger. Then I modify the code（eval and eval_util） and point to AI_Challenger, due to the python 2.7 version, I also change my project version to Python 2.7(conda based).


[https://github.com/AIChallenger/AI_Challenger_2017/tree/master/Evaluation/caption_eval](url)

eval_utils.py:
```
sys.path.append("AI_Challenger/Evaluation/caption_eval")
from coco_caption.pycxtools.coco import COCO
from coco_caption.pycxevalcap.eval import COCOEvalCap

bad_endings = ['a','an','the','in','for','at','of','with','before','after','on','upon','near','to','is','are','am']
bad_endings += ['the']

def getCOCO(dataset):
    # if 'coco' in dataset:
    #     annFile = 'coco-caption/annotations/captions_val2014.json'
    # elif 'flickr30k' in dataset or 'f30k' in dataset:
    #     annFile = 'data/f30k_captions4eval.json'
    # elif 'chinese' in dataset:
    annFile = 'data/chinese_eval.json'

    return COCO(annFile)

```

Then I use the self-critical.pytorch 's code (eval.py eval_util.py dataloader.py) to evaluate. But get the same Error. 

So, should I use the Image_Captioning_AI_Challenger eval_util.py code directly or modify the self-critical.pytorch's eval_util.py with reference Image_Captioning_AI_Challenger's code? The latter option was difficult for me ：）Because I really want to do this work base on self-critical.pytorch (due to the pytorch version is higher).

I also try to use Image_Captioning_AI_Challenger's code following by readme to evaluate. The evaluate on test split:

```
$ python eval.py --dump_images 0 --num_images -1 --split test  --model log_dense_box_bn/model-best.pth --language_eval 1 --beam_size 5 --temperature 1.0 --sample_max 1  --infos_path log_dense_box_bn/infos_dense_box_bn-best.pkl
```

but got below result
```
input_json
input_fc_dir
input_box_dir
Traceback (most recent call last):
  File "eval.py", line 113, in <module>
    assert vars(opt)[k] == vars(infos['opt'])[k], k + ' option not consistent'
AssertionError: input_box_dir option not consistent
```

code is:
```
ignore = ["id", "batch_size", "beam_size", "start_from", "language_eval"]


for k in vars(infos['opt']).keys():
    if k not in ignore:
        if k in vars(opt):
            print(k)
            assert vars(opt)[k] == vars(infos['opt'])[k], k + ' option not consistent'
        else:
            vars(opt).update({k: vars(infos['opt'])[k]}) # copy over options from model
```

The two project 's training process is smooth but the evaluating process is not. Image_Captioning_AI_Challenger can do evaluate with enable --language_eval 1 when training. resut is shown bellow:

Do you have any suggestions?  :)

```
evaluating validation preformance... 63/50 (1.587868)
loading annotations into memory...
0:00:04.752519
creating index...
index created!
Loading and preparing results...     
DONE (t=0.31s)
creating index...
index created!
50
tokenization...
PTBTokenizer tokenized 3452 tokens at 57868.89 tokens per second.
PTBTokenizer tokenized 642 tokens at 19181.31 tokens per second.
setting up scorers...
computing Bleu score...
{'reflen': 599, 'guess': [593, 543, 493, 443], 'testlen': 593, 'correct': [459, 288, 173, 105]}
ratio: 0.989983305508
Bleu_1: 0.766
Bleu_2: 0.634
Bleu_3: 0.519
Bleu_4: 0.426
computing Rouge score...
ROUGE_L: 0.629
computing CIDEr score...
CIDEr: 1.338
model saved to log_dense_box_bn/model.pth

```

**Comment by ruotianluo** [comment]
you can add input_box_dir into ignore.

**Comment by andrewcao95** [comment]
Great!  I will try soon. Another question want to know that the dataloading processing in self-critical.pytorch is very quick but slow in Image_Captioning_AI_Challenger.  Is this because of the two project using different pytorch and CUDA versions ?

```
DataLoader loading h5 file:  data/chinese_bu_fc data/chinese_bu_box  data/chinese_talk_label.h5
max sequence length in data is 20
read 240000 image features
assigned 220000 images to split train
assigned 10000 images to split val
assigned 10000 images to split test

```

**Comment by ruotianluo** [comment]
It's likely not.

**Comment by Joey-Twan** [comment]
You can try to delete an eval_result folder after running eval.py
