### ISSUE TITLE
Does the images need to be resized first?

### ISSUE THREAD

**Issue by watsonyanghx** [ruotianluo/self-critical.pytorch#17]
Does the images need to be resized first? Start learning pytorch, don't find the resize code when input image to resnet.

**Comment by ruotianluo** [comment]
In the paper, the image features are pre-extracted. And when extracting the feature, the images are directly fed into the convnet without resizing.

**Comment by watsonyanghx** [comment]
OK, got it, thanks. 

Another question, in order to further improve the score, finetuning the CNN part is needed, should all the variables be finetuned? Or only the last several layers? Which will be better?

**Comment by watsonyanghx** [comment]
thank you!
