### ISSUE TITLE
scores in Model Zoo

### ISSUE THREAD

**Issue by fawazsammani** [ruotianluo/self-critical.pytorch#170]
hi @ruotianluo 
I'd like to kindly ask, are the scores reported in Model Zoo for Transformer (for XE, without sc/nsc) as `Transformer | 1.113 | 0.2045` using beam search? Or only greedy evaluation? If using beam search, may you please tell me the beam size you set?

**Comment by ruotianluo** [comment]
It's should be beam size 5
