### ISSUE TITLE
noam optimizer doesn't have learning_rate

### ISSUE THREAD

**Issue by yilinyang7** [ruotianluo/self-critical.pytorch#171]
Hello Ruotian,

From my debug, it seems following lines of codes didn't set the initial lr for noam optimizer:

https://github.com/ruotianluo/self-critical.pytorch/blob/728ee86fc49b03721ed17f26d5b07f48a6b21927/misc/utils.py#L442-L443

**Comment by ruotianluo** [comment]
You are absolutely correct. That's necessary for transformer.

**Comment by yilinyang7** [comment]
Hello Ruotian,

I further find out that the "factor" is supposed to serve as "initial lr" in following codes:

https://github.com/ruotianluo/self-critical.pytorch/blob/master/misc/utils.py#L389-L391

From the codes, it seems that the noam optimizer would "ignore" the first batch (lr=0), and initialize the lr after first batch at:https://github.com/ruotianluo/self-critical.pytorch/blob/master/train.py#L181

**Comment by ruotianluo** [comment]
yes. you are right. This whole thing is inherited from original attention is all you need paper.

**Comment by yilinyang7** [comment]
Thank you for your instant reply and clarification:)
