### ISSUE TITLE
Error  when Evaluate on COCO test set

### ISSUE THREAD

**Issue by cfhyxxj** [ruotianluo/self-critical.pytorch#176]
when I write this order,something wrong with it.
DataLoader loading json file:  data/cocotest.json
vocab size is  9487
DataLoader loading h5 file:  data/cocotest_bu_fc data/cocotest_bu_att data/cocotalk_box none
read 40775 image features
assigned 0 images to split train
assigned 0 images to split val
assigned 40775 images to split test
Traceback (most recent call last):
  File "eval.py", line 100, in <module>
    loader = DataLoader(opt)
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/dataloader.py", line 303, in __init__
    self.iters[split] = iter(self.loaders[split])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 746, in __init__
    self._try_put_index()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 861, in _try_put_index
    index = self._next_index()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/content/gdrive/Shared drives/cfhyxxj798577670/1/dataloader.py", line 370, in __next__
    elem = (self.index_list[self.iter_counter], self.iter_counter+1, wrapped)
IndexError: list index out of range

**Comment by WilsonAir** [comment]
Got the same issue too!

**Comment by ruotianluo** [comment]
Weird:
```

        if self.iter_counter == len(self._index_list):
            self._reset_iter()
            if self.wrap:
                wrapped = True
            else:
                raise StopIteration()
        elem = (self._index_list[self.iter_counter], self.iter_counter+1, wrapped)
```
In principle the if statement above should assure that the iter_coutner is within range.

**Comment by sssilence** [comment]
> Got the same issue too!

Excuse me.I encountered the same problem as you. How do you slove it?Thanks!

**Comment by kaelsunkiller** [comment]
> Weird:
> 
> ```
> 
>         if self.iter_counter == len(self._index_list):
>             self._reset_iter()
>             if self.wrap:
>                 wrapped = True
>             else:
>                 raise StopIteration()
>         elem = (self._index_list[self.iter_counter], self.iter_counter+1, wrapped)
> ```
> 
> In principle the if statement above should assure that the iter_coutner is within range.

I entered the same problem.The cause is the number of images in `val` split is 0, which leads to an empty `self._index_list`. So the index 0 overflowed. You may give a check before this statement.

**Comment by kaelsunkiller** [comment]
And btw, the key name in the npz file in the `cocotest_bu_att`(preprocessed, download from your link) is `'z'` but not `'feat'`, this will lead to another error in 
`dataloader.py, line 35`:
`self.loader = lambda x: np.load(x)['feat']`
may be you can give a hint to the people who are willing to use your preprocessed npz files.

**Comment by ruotianluo** [comment]
Thanks. I will fix it.
