### ISSUE TITLE
Failed import of misc.utils utils in prepro_ngrams.py

### ISSUE THREAD

**Issue by jpanaro** [ruotianluo/self-critical.pytorch#179]
Hello. When trying to execute the following statement:
`$ python scripts/prepro_ngrams.py --input_json data/dataset_coco.json --dict_json data/cocotalk.json --output_pkl data/coco-train --split train
`
I receive the following error:
```
Traceback (most recent call last):
  File "scripts/prepro_ngrams.py", line 12, in <module>
    import misc.utils as utils
ImportError: No module named misc.utils
```
I attempted to solve it by using:
```
sys.path.insert(0, '<path to misc folder>')
```
However this resulted in the following error:
```
Traceback (most recent call last):
  File "scripts/prepro_ngrams.py", line 13, in <module>
    import utils
  File "<path to utils.py>", line 12, in <module>
    from .rewards import get_scores, get_self_cider_scores
ValueError: Attempted relative import in non-package
```

Any help would be appreciated.

**Comment by ruotianluo** [comment]
The simplest solution is to copy prepro ngrams to the self critical pytorch directory.

**Comment by jpanaro** [comment]
> The simplest solution is to copy prepro ngrams to the self critical pytorch directory.

Thank you for the quick response! That solved that issue. Unfortunately I ran into a similar issue not too far down the road when running
```
python scripts/prepro_labels.py --input_json data/dataset_coco.json --output_json data/cocotalk.json --output_h5 data/cocotalk
``` 
and was left with the error
```
Traceback (most recent call last):
  File "scripts/prepro_labels.py", line 38, in <module>
    import torchvision.models as models
ImportError: No module named torchvision.models
```
Which I was unable to solve using the same method.

**Comment by ruotianluo** [comment]
you need to install torchvision

**Comment by jpanaro** [comment]
Oh, looks like the remote server I was on did not support external installations thank you for the help!
