### ISSUE TITLE
[cider-D] Could not find pyciderevalcap in "Microsoft COCO Caption Evaluation"

### ISSUE THREAD

**Issue by coderSkyChen** [ruotianluo/self-critical.pytorch#19]
Hi,
In Microsoft COCO Caption Evaluation,there only exists pycocoevalcap, no pyciderevalcap
I'm new to the caption metrics, does the cider means cider-D?

(1)  from pyciderevalcap.ciderD.ciderD import CiderD    yours
(2)from pycocoevalcap.cider.cider import CiderD  mine
 
Can i import CiderD in the form of (2)?  or where can i find the pyciderevalcap code?  since i can't find it in github...

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/self-critical.pytorch#train-using-self-critical

I used a slightly-modified cider which is more efficient.

**Comment by coderSkyChen** [comment]
Thanks a lot!
