### ISSUE TITLE
复现指标比原论文还要高

### ISSUE THREAD

**Issue by zzcaptain** [ruotianluo/self-critical.pytorch#190]
你好，非常感谢你提供的代码和预训练模型。这里有个问题，在使用你给的updown模型纯粹用cross entropy训练最终在karpathy测试集上的cider得分竟然达到113.8，超过了原论文的113.5，请问这个是正常现象吗

**Comment by ruotianluo** [comment]
正常的。0.3的差距不算很大

**Comment by zzcaptain** [comment]
好的，我是个小白看到这个结果还以为自己哪里错了来着，谢谢您，对我的帮助真的很大！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ruotian(RT) Luo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月1日(星期五) 上午10:08
收件人:&nbsp;"ruotianluo/self-critical.pytorch"<self-critical.pytorch@noreply.github.com&gt;;
抄送:&nbsp;"1014402909"<1014402909@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ruotianluo/self-critical.pytorch] 复现指标比原论文还要高 (#190)





 
正常的。0.3的差距不算很大

**Comment by zzcaptain** [comment]
您好，我用您的代码复现updown模型用self-critical训练后在karpathy测试集上的cider得分达到124.8，好像超过了原论文的120.1比较多，请问这个是正常现象吗

**Comment by ruotianluo** [comment]
你用的这个config嘛https://github.com/ruotianluo/self-critical.pytorch/blob/master/configs/updown_sc.yml

那还挺高的。

**Comment by zzcaptain** [comment]
请问这个配置文件是从0epoch开始还是从30epoch开始的呀

**Comment by zzcaptain** [comment]
我是先XL训练了30个epoch，然后手动改配置文件learning_rate=5e-5，learning_rate_decay_start=30让它继续训练到60epoch的

**Comment by ruotianluo** [comment]
这个配置文件可以从头训练。
如果你是这样设置的话，1.24也是有可能的。updown long可以到1.28

**Comment by zzcaptain** [comment]
谢谢你指出的问题，可以问一下updown long是啥意思或者哪篇论文里的吗，第一次接触这个词

**Comment by ruotianluo** [comment]
你看我的model zoo。就是训练的长一点就效果好一点

**Comment by zzcaptain** [comment]
好的，再次感谢！
