### ISSUE TITLE
ModuleNotFoundError: No module named 'misc'

### ISSUE THREAD

**Issue by Mollylulu** [ruotianluo/self-critical.pytorch#191]
![misc_error](https://user-images.githubusercontent.com/26273127/80866043-2a078700-8cbf-11ea-8d4d-d52796f107f1.png)
hi~ Ruotian, when I extract the feature, It reported that could not found misc module, which has been in this directory. What's wrong may be with this? Thanks in advance.

**Comment by ruotianluo** [comment]
Try copying the prepro_feats into the root directory.

**Comment by Mollylulu** [comment]
> Try copying the prepro_feats into the root directory.

I think it works :)
