### ISSUE TITLE
Running BU training meets Error

### ISSUE THREAD

**Issue by Mollylulu** [ruotianluo/self-critical.pytorch#192]
![training](https://user-images.githubusercontent.com/26273127/80868612-6d1d2680-8cce-11ea-9690-76b27aac27f5.jpg)

`python train.py --id fc --caption_model newfc --input_json /data/cocotalk.json --inp ut_fc_dir /data/cocobu_fc --input_att_dir /data/cocobu_att --input_label_h5 /data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log_fc --save_checkpoint_every 6000 --val_images_use 5000 --max_epochs 30
`

Sorry, Ruotian, bother you again. When I run this training cmd, I got the error like above. Seems like strange about the different data type. May something wrong?  Again, really thank you soo much :)

**Comment by ruotianluo** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/16023153/80868635-994e8e00-8c61-11ea-9ab6-5eb479b13b83.png">
Tensor should have ndim?

**Comment by Mollylulu** [comment]
> <img alt="image" width="236" src="https://user-images.githubusercontent.com/16023153/80868635-994e8e00-8c61-11ea-9ab6-5eb479b13b83.png">
> 
> Tensor should have ndim?

![tensor](https://user-images.githubusercontent.com/26273127/80869133-21b84780-8cd1-11ea-9ce5-16edcc1b6ff1.png)
ndim attr gives me thought about numpy data type. where may be wrong?

**Comment by ruotianluo** [comment]
Don't add brankets

**Comment by Mollylulu** [comment]
> Don't add brankets

sorry for the before wrong picture. I mean this :point_down: 

<img src="https://user-images.githubusercontent.com/26273127/80907972-2e2eb580-8d4e-11ea-8069-8fb514efb82d.png" width="300" height="120">

**Comment by Mollylulu** [comment]
I got it. Wrong with the torch version. :expressionless:
