### ISSUE TITLE
Git problems with Submodule Cider

### ISSUE THREAD

**Issue by caryleo** [ruotianluo/self-critical.pytorch#194]
你好！由于我的英语还不够好，为保证准确描述问题，这里我直接使用中文。我使用了您的CodeBase，在试图使用Cider多样性指标时，出现了`cider.my_self_cider`未定义的错误，具体输出如下（使用Windows远程桌面无法直接复制，因此直接截图呈现）：

Hello! Since my English is not good enough, in order to ensure an accurate description of the problem, I use Chinese directly here. I used your CodeBase. When trying to use the Cider diversity indicator, I got an undefined error of `cider.my_self_cider`. The specific output is as follows (using Windows Remote Desktop cannot directly copy output, so the screenshot is presented here):

![image](https://user-images.githubusercontent.com/18438538/81287820-031dcc00-9096-11ea-926d-e07d23e846d4.png)

我在进行`git clone`时，使用了`--recuresive`选项直接克隆submodule，下载到的版本中没有`cider.my_self_cider`的实现，又使用了直接在文件夹下`git clone`该库同样无法找到这个方法的实现。
直到我进入到commit记录里发现，该方法实现对应的commit记录编号为`e9b736d038d39395fa2259e39342bb876f1cc877`，该commit记录可以从`self-critical.pytorch`工程的链接页面下找到（共36个commit记录），但是如果直接从`cider`工程下打开的话，是查询不到该commit记录的（共34个commit记录）。

When I used `git clone` command, I used the` --recuresive` option to directly clone the submodule. The downloaded version did not implement `cider.my_self_cider`. Then I used `git clone` directly under the folder, the implementation of this method can also not be found.
I checked the commit record and found that the corresponding commit record ID of this method implementtion is `e9b736d038d39395fa2259e39342bb876f1cc877`. This commit record can be found from the link page of the` self-critical.pytorch` project (36 commit records in total), but When I opened it directly from the `cider` project, I cannot find the commit record (34 commit records in total).

我对git的使用尚不熟练，故不知造成commit记录不同步的原因，特来询问。希望能够得到您的解答，十分感谢！

I am still unskilled in the use of git, so I don’t know the reason why the commit record is not synchronized. Hope to get your answer, thank you very much!

**Comment by caryleo** [comment]
My bad! I ignored the branch things! This project need to check out to branch `self-cider`.

**Comment by ruotianluo** [comment]
你把 self cider的部分删掉吧
那个默认是不用的


Ruotian Luo

**Comment by caryleo** [comment]
请问你是指`cider.my_self_cider`这个方法吗？因为我想使用Self-Cider这个多样性指标，删除这个方法的话是不是就用不了了呀？

**Comment by ruotianluo** [comment]
哦，那你用吧，别删了

**Comment by caryleo** [comment]
好的，十分感谢你的解答！
