### ISSUE TITLE
CUDA out of memory in self-critical training but not in xe

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#195]
Hello. I am using GTX2080 Ti with 11GB memory. I trained the model using xe and it works fine. But then when I run self-critical, I get CUDA out of memory. How come the model can fit in xe training but not in rl training? It is the same model with the same number of parameters. Any advice would help

**Comment by ruotianluo** [comment]
Which model are you using. For transformer, sc training repuires more memory than xe training.

**Comment by homelifes** [comment]
i'm using the transformer model. May I know why sc training requires more? The data isn't increased, and the model parameters aren't increased as well.

**Comment by homelifes** [comment]
and also may I also know that is it fine to train xe on the bigger batch size and then train self-critical with a smaller batch size? Or will using different batch sizes effect performance?

**Comment by ruotianluo** [comment]
The reason is the current implementation doesn't cache the intermediate states. 
Here is a reference: https://huggingface.co/transformers/quickstart.html#using-the-past

If using this, the memory usage can be much lower.


You can implement it on your own. I have implemented it, https://gist.github.com/ruotianluo/23f3e67853de2e94089936e2d12ab3fe.

But I am sure it's buggy. You probably need to debug it a little bit, to findout what's the problem.

**Comment by homelifes** [comment]
Alright, I will have a look. What about decreasing the batch size in self-critical training? That will also solve the problem. Or will using different batch sizes effect performance?

**Comment by ruotianluo** [comment]
You can definitely train with smaller batch size. I can't say anything about the performance, because it really varies. Usually larger batch size is better, but also you need to tune the learning rate accordingly. If not changing accordingly, the performance may be worse.

It's really hard to say.

**Comment by homelifes** [comment]
Alright. I will investigate on this further. Thanks a lot for your help

**Comment by homelifes** [comment]
@ruotianluo sorry for opening this issue again. However I have two questions about the cache. 
1- The cache part has to be done in the masked **self attention** in the decoder, and **not** in the context/image attention in the decoder, which is the second multihead attention in the decoder. Because in the context attention the sequence length is the number of image features (e.x 100). 

2- If I want to save memory, in addition to 1, can I project the keys/values one time during the context attention and use it for all the decoding process (for all words when decoding in self-critical). Because it's always going to project the same keys/values (which are the encoder output) in which their shape doesn't change. 

Thanks a lot for your help!

**Comment by ruotianluo** [comment]
1 yes, cache is only applied in decoder. 
2 yes. That's actually what I am trying to do in the gist

**Comment by ruotianluo** [comment]
Add to 1.  The variable memory is the image feature and it's only computed once.

**Comment by homelifes** [comment]
It’s only computed once (Transformer encoder is run once), but when attending over it in the decoder (second multihead attention in the decoder), there is no need to store the past for keys and values as we did in the first multihead attention in the decoder (the Masked self attention), because the sequence length (100) is fixed during the decoding, right?

**Comment by ruotianluo** [comment]
I think I have tried cached the keys and values for encoder. I dropped it because I failed to make it work. Yes, you can definitely try.

**Comment by ruotianluo** [comment]
I updated it, https://gist.github.com/ruotianluo/23f3e67853de2e94089936e2d12ab3fe. This seems to be working.
