### ISSUE TITLE
I wonder if the id of the end token is 0?

### ISSUE THREAD

**Issue by eduOS** [ruotianluo/self-critical.pytorch#2]
Hi, Dr. Luo,       
I am confused by the following code:       
```python
            if t >= 2:
                # stop when all finished
                if t == 2:
                    unfinished = it > 0
                else:
                    unfinished = unfinished * (it > 0)
                if unfinished.sum() == 0:
                     break
```
I guess according to the above snippet that the id of the end token is 0, right? I cannot verify that since the dictionary is loaded from the binary file. 

Please help point in the right direction, thanks very much.

**Comment by ruotianluo** [comment]
0 is end token. (note that start token us also 0)

**Comment by eduOS** [comment]
Got it. Thanks very much for your help.
