### ISSUE TITLE
question about unfininshed in sample function

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#201]
Hello @ruotianluo . Thanks for your code. I have a question about the below portion of the code:
```
            # stop when all finished
            if t == 0:
                unfinished = it != self.eos_idx
            else:
                it[~unfinished] = self.pad_idx # This allows eos_idx not being overwritten to 0
                logprobs = logprobs * unfinished.unsqueeze(1).float()
                unfinished = unfinished * (it != self.eos_idx)
            seq[:,t] = it
            seqLogprobs[:,t] = logprobs
            # quit loop if all sequences have finished
            if unfinished.sum() == 0:
                break
```
Here the end token is being replaced with the pad according to the calculation of `unfinished` from the **previous timestep**: `it[~unfinished] = self.pad_idx`, since you are using the `unfinished` computed from the previous timestep 

As a result, when the current timestep predicts the `eos`, it will not be replaced by the `pad_idx` because the loop will break since the updated `unfinished.sum()` will be zero. So the `seq` matrix will save the `eos` rather than `pad_idx`. In your code, it does not matter because the `eos` is 0 anyways. But in my code, I set the `eos` to another value because of my application requirement. So how can I avoid the issue above? Can i just place the unfinished calculation at the begining of `else`, like this:

```
            if t == 0:
                unfinished = it != self.eos_idx
            else:
                unfinished = unfinished * (it != self.eos_idx)   # placed here rather than at the end
                it[~unfinished] = self.pad_idx 
                logprobs = logprobs * unfinished.unsqueeze(1).float()   
```
Thanks!

**Comment by ruotianluo** [comment]
So you want the eos to be replaced by pad,  right?
If so,  your modification is correct
