### ISSUE TITLE
About  cocotest_bu_fc.tar file 

### ISSUE THREAD

**Issue by Jordan-5i** [ruotianluo/self-critical.pytorch#202]
I download cocotest_bu_fc.tar, the number of the .npy files is 81435, not 40755.   In cocotest.json file, the number of images is 40775.  Why are their numbers inconsistent？

**Comment by ruotianluo** [comment]
I believe 40755 comes from 2014 test, and 81435 comes from 2015 test. I forgot which one is actually the test for coco captioning.

**Comment by ruotianluo** [comment]
I think 2014 is for captioning. So the cocotest is correct. The tar file contains some useless ones.
