### ISSUE TITLE
Why using torch.max in LSTMCore

### ISSUE THREAD

**Issue by peterfind** [ruotianluo/self-critical.pytorch#203]
Hello~ @ruotianluo 
I am wondering why there is `torch.max` operation in `LSTMCore`, rather than a simple `narrow`.
What is the reason that we max two tensors into one?
The original code is here:
https://github.com/ruotianluo/self-critical.pytorch/blob/5fdf374f1e8f814598ce0b2540c36a047cab2b2a/captioning/models/FCModel.py#L34-L36

**Comment by ruotianluo** [comment]
It's the model described in the self critical sequence training paper.
