### ISSUE TITLE
should the optimizer state dic be loaded in self-critical?

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#204]
Hello @ruotianluo .
After training with XE, and when we want to start self-critical training, it is clear that we should load the model. But should the optimizer state dictionary be loaded from the XE ckpt as well? In your code, you load it, but I saw other codes don't and they just define a new optimizer from scratch.

Thanks

**Comment by ruotianluo** [comment]
Yes, that's what I did. I think there is no big difference.

**Comment by homelifes** [comment]
Actualy you are not defining a new one. You are loading the old one, as here:
```
    if opt.start_from is not None and os.path.isfile(os.path.join(opt.start_from,"optimizer.pth")):
        optimizer.load_state_dict(torch.load(os.path.join(opt.start_from, 'optimizer.pth')))
```

**Comment by ruotianluo** [comment]
`In your code, you load it`

I am agreeing this

**Comment by homelifes** [comment]
sorry. Alright thanks for your reply. I don't think it matters but i just wanted to check
