### ISSUE TITLE
question on model zoo

### ISSUE THREAD

**Issue by homelifes** [ruotianluo/self-critical.pytorch#206]
Hi, Thanks a lot for your code and for running the models.
For the model Trained with vilbert-12-in-1 feature which achieves 1.158, may you please tell me the self-critical results if you ran them?

**Comment by homelifes** [comment]
The cider score improves from 1.277 to 1.3, which is quite good. May I know is this trained with new self-critical or the normal self-critical?

**Comment by ruotianluo** [comment]
It is the new self critical and also train with 40 epochs.

**Comment by ruotianluo** [comment]
it's the transformer_nscl

**Comment by homelifes** [comment]
oh i see...0.002 cider point improvement. Not significant. Thanks a lot for your help
Regards
