### ISSUE TITLE
the meaning of "restval"

### ISSUE THREAD

**Issue by gctian** [ruotianluo/self-critical.pytorch#21]
hi, in file prepro_ngrams.py , img['split'] == 'restval' ,what's the meaning of "restval" ? restval not in "train val test".

**Comment by ruotianluo** [comment]
we use restval as training set.

**Comment by gctian** [comment]
if so ,why "(params['split'] == 'train' and img['split'] == 'restval')" ,not just"(params['split'] == 'train' )".du you have 'restval' flag in your dataset ?

**Comment by ruotianluo** [comment]
yes, there are restval in the dataset.
