### ISSUE TITLE
ModuleNotFoundError: No module named 'captioning'

### ISSUE THREAD

**Issue by Rubatoo** [ruotianluo/self-critical.pytorch#212]
hi, when i do 'Image features option 1: Resnet features', i got this error.

Traceback (most recent call last):
  File "scripts/prepro_feats.py", line 38, in <module>
    from captioning.utils.resnet_utils import myResnet
ModuleNotFoundError: No module named 'captioning'

how do i fix it?

**Comment by ruotianluo** [comment]
I forgot to update readme. sorry.

You can run `python -m pip install -e .`

**Comment by Rubatoo** [comment]
when i run 'python -m pip install -e captioning' , i got this error

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/bg/BG/self-critical.pytorch/captioning

**Comment by Rubatoo** [comment]
but setup.py is being in self-critical.pytorch folder

**Comment by zl535320706** [comment]
I run "python setup.py install" fix it.
