### ISSUE TITLE
KeyError: 'masks'

### ISSUE THREAD

**Issue by Rubatoo** [ruotianluo/self-critical.pytorch#214]
when i try to evaluate on raw images, i got this error.

Traceback (most recent call last):
  File "tools/eval.py", line 117, in <module>
    vars(opt))
  File "/home/bg/BG/self-critical.pytorch/captioning/utils/eval_utils.py", line 161, in eval_split
    tmp = [data['fc_feats'], data['att_feats'], data['labels'], data['masks'], data['att_masks']]
KeyError: 'masks'

how do i fix it?

**Comment by ruotianluo** [comment]
Try replaceing https://github.com/ruotianluo/self-critical.pytorch/blob/master/captioning/data/dataloaderraw.py#L129g

with 

```
        data['labels'] = None
        data['masks'] = None
```

**Comment by Rubatoo** [comment]
thank you!
but i have something error.

Traceback (most recent call last):
  File "tools/eval.py", line 74, in <module>
    lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
  File "/home/bg/BG/self-critical.pytorch/captioning/utils/eval_utils.py", line 83, in language_eval
    mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
ZeroDivisionError: division by zero

**Comment by ruotianluo** [comment]
Set language_eval to 0 in arguments.

**Comment by Rubatoo** [comment]
i did , but it doesn't work

**Comment by ruotianluo** [comment]
Then delete these for now.

**Comment by windspirit95** [comment]
> thank you!
> but i have something error.
> 
> Traceback (most recent call last):
> File "tools/eval.py", line 74, in
> lang_stats = eval_utils.language_eval(opt.input_json, predictions, n_predictions, vars(opt), opt.split)
> File "/home/bg/BG/self-critical.pytorch/captioning/utils/eval_utils.py", line 83, in language_eval
> mean_perplexity = sum([_['perplexity'] for _ in preds_filt]) / len(preds_filt)
> ZeroDivisionError: division by zero

I delete the previous result file (.pth) in eval_results folders and problem solved, as described in his comment:
# if results existed, then skip, unless force is on
Since some bugs happened when existing result file, you could also comment from line 61 to line 76, or using try......except: pass to ignore this part :)
