### ISSUE TITLE
How to evaluate on ohter dataset

### ISSUE THREAD

**Issue by ly201802004** [ruotianluo/self-critical.pytorch#219]
hi, @ruotianluo, sorry to bother you.
I want to train and evaluate my own network on RSICD dataset. This dataset has dataset_rsicd.json file, which is similar to dataset_coco.json. However it doesn't has an annotation file like captions_val2014.json. Now i have successfully train my network, but how can i get BLEU/METEOR scores?
Thanks a lot!

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/self-critical.pytorch/blob/master/scripts/prepro_reference_json.py
