### ISSUE TITLE
An emergency

### ISSUE THREAD

**Issue by upccpu** [ruotianluo/self-critical.pytorch#22]
Hi luo,
       i deployed your code on a new dataset.  It is bigger than COCO.  With the XE loss, the results is ok. But, when i tried SCST after 20 epoches, the negative rewards did't seem to go down too much. In addition, i  tried to use a learning parameter to balance XE loss and SCST loss( β*(SCST_loss)+(1-β)*(XE_loss)), however, it also did't work. Can you give me some advice. And, I need to correct your topdown work, the input of the att_lstm is not concat(xt,fc_feats,h2) , the fc_feats shoud be replaced by the mean of the pool5 features(resnet,  bottom up....).

**Comment by ruotianluo** [comment]
try 30 epochs.
