### ISSUE TITLE
Train using self critical

### ISSUE THREAD

**Issue by alibabadoufu** [ruotianluo/self-critical.pytorch#225]
when I run this code:
`python scripts/prepro_ngrams.py --input_json data/dataset_coco.json --dict_json data/cocotalk.json --output_pkl data/coco-train --split train`

I got this error:

`AttributeError: 'CiderScorer' object has no attribute 'document_frequency'`

Anyone experienced the same problem?

**Comment by ruotianluo** [comment]
Are you using the cider submodule in the repo?

**Comment by alibabadoufu** [comment]
> Are you using the cider submodule in the repo?

Just did

`git submodules init
git submodules update`

Thanks!
