### ISSUE TITLE
Report errors: distinct length when stack the sequences in eval_utils.py | import missing in eval_multi.py

### ISSUE THREAD

**Issue by kaelsunkiller** [ruotianluo/self-critical.pytorch#229]
1. eval_utils.py line 248

>     _sents = utils.decode_sequence(model.vocab, torch.stack([model.done_beams[k][_]['seq'] for _ in range(sample_n)]))

When using beam search for sampling multiple captions in eval_utils.py the sequences in `model.done_beams` have different lengths due to the early stop (I guess), so there will be an error about this.

I made a change like this, I hope it's right:

>     _sents = utils.decode_sequence(model.vocab, nn.utils.rnn.pad_sequence([model.done_beams[k][_]['seq'] for _ in range(sample_n)], batch_first=True))

2. eval_multi.py line 17

> from eval_utils import getCOCO

missing the point `.` , will get a No Module error, should be:

> from .eval_utils import getCOCO

**Comment by ruotianluo** [comment]
Thanks! I will check.
