### ISSUE TITLE
每次训练到24个epoch时会遇到Terminating BlobFetcher

### ISSUE THREAD

**Issue by Shi-Yuyao** [ruotianluo/self-critical.pytorch#240]
您好，请问一下使用您的code，设定25个epoch，但是每次在跑到第24个时，会出现Terminating BlobFetcher的问题，例如：
`iter 157343 (epoch 24), train_loss = 0.191, time/batch = 1.118
Terminating BlobFetcher`
没有显示任何报错，但是会终止训练，请问是什么问题，谢谢！

**Comment by ruotianluo** [comment]
因为是epoch0开始的，所以这是epoch24的最后一个iteration

**Comment by Shi-Yuyao** [comment]
> 因为是epoch0开始的，所以这是epoch24的最后一个iteration

好的，我竟然忽略了这个问题，非常感谢！祝您科研一切顺利！
