### ISSUE TITLE
do evaluation

### ISSUE THREAD

**Issue by AdamTTong** [ruotianluo/self-critical.pytorch#25]
when i do evaluation on the topdown pretrained model,i got "No such file or directory: 'data/cocotalk_fc/391895.npy'",can you give me some advice?

**Comment by ruotianluo** [comment]
Do you actually have that file? The file should be there you did preprocessing correctly

**Comment by AdamTTong** [comment]
Thank you for you reply,i find the mistake . And the batch_size increase to 64 have any Influence ?

**Comment by ruotianluo** [comment]
Could be better
