### ISSUE TITLE
error on flickr30k eval

### ISSUE THREAD

**Issue by xmu-xiaoma666** [ruotianluo/self-critical.pytorch#251]
log like bellow:

```
Traceback (most recent call last):
  File "tools/train.py", line 299, in <module>
    train(opt)
  File "tools/train.py", line 253, in train
    dp_model, lw_model.crit, loader, eval_kwargs)
  File "/home/mayiwei/extraSpace/TIP/self-critical.pytorch/captioning/utils/eval_utils.py", line 207, in eval_split
    predictions.pop()
IndexError: pop from empty list
```

**Comment by ruotianluo** [comment]
Not sure why this would happen.

**Comment by xmu-xiaoma666** [comment]
> Not sure why this would happen.

When I use Flickr30k to train the model, the performance of the second stage(self-critical or new-self-critical) will drop quickly. Do you know what this happens?

**Comment by ruotianluo** [comment]
It worked for me:

This was the script I ran.

xe:
`
python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 50 --beam_size 1 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use 5000 --max_epochs 30
`

nsc:
`python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 100 --beam_size 1 --learning_rate 4.3e-5 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use -1 --max_epochs 100 --structure_after 28 --structure_sample_n 1 --structure_loss_weight 1 --structure_loss_type new_self_critical --cached_tokens f30k-train-idxs`

**Comment by ruotianluo** [comment]
![image](https://user-images.githubusercontent.com/16023153/118432854-4cd4c580-b69f-11eb-88f2-afe80578289d.png)

**Comment by xmu-xiaoma666** [comment]
> It worked for me:
> 
> This was the script I ran.
> 
> xe:
> `python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 50 --beam_size 1 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use 5000 --max_epochs 30`
> 
> nsc:
> `python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 100 --beam_size 1 --learning_rate 4.3e-5 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use -1 --max_epochs 100 --structure_after 28 --structure_sample_n 1 --structure_loss_weight 1 --structure_loss_type new_self_critical --cached_tokens f30k-train-idxs`

Thank you very much.
I surprisingly find that the value of batch size affects the performance a lot. Under Flickr30k, I use a batch size of 10 in the second stage(sc, nsc), the performance drops quickly. However, if I use a batch size of 50, the performance will improve. Do you know why this happens? Or do you know which value of batch size works best in the second stage?

**Comment by xmu-xiaoma666** [comment]
> It worked for me:
> 
> This was the script I ran.
> 
> xe:
> `python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 50 --beam_size 1 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use 5000 --max_epochs 30`
> 
> nsc:
> `python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 100 --beam_size 1 --learning_rate 4.3e-5 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use -1 --max_epochs 100 --structure_after 28 --structure_sample_n 1 --structure_loss_weight 1 --structure_loss_type new_self_critical --cached_tokens f30k-train-idxs`
![img1](https://user-images.githubusercontent.com/33897496/118478889-fa4ce500-b742-11eb-9842-53ebeaf50c1c.png)

**Comment by xmu-xiaoma666** [comment]
> It worked for me:
> 
> This was the script I ran.
> 
> xe:
> `python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 50 --beam_size 1 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use 5000 --max_epochs 30`
> 
> nsc:
> `python train.py --id $id --caption_model att2in2 --input_json data/f30ktalk.json --input_label_h5 data/f30ktalk_label.h5 --input_fc_dir data/f30kbu_fc --input_att_dir data/f30kbu_att.pth --seq_per_img 5 --batch_size 100 --beam_size 1 --learning_rate 4.3e-5 --checkpoint_path $ckpt_path $start_from --save_checkpoint_every 3000 --language_eval 1 --val_images_use -1 --max_epochs 100 --structure_after 28 --structure_sample_n 1 --structure_loss_weight 1 --structure_loss_type new_self_critical --cached_tokens f30k-train-idxs`

![img1](https://user-images.githubusercontent.com/33897496/118478944-0b95f180-b743-11eb-9623-342ee8e6a4c8.png)


This is my result.
Either batch size of 50 or 10, the performance will still drop.
