### ISSUE TITLE
关于nsc

### ISSUE THREAD

**Issue by hasky123** [ruotianluo/self-critical.pytorch#253]
您好，请问nsc是《Meshed-Memory Transformer for Image Captioning》中的强化学习方法吗？
![image](https://user-images.githubusercontent.com/44098877/122063922-444ce780-ce23-11eb-9551-189e34f04757.png)

**Comment by ruotianluo** [comment]
怎个式子是等价的，但是他sample用的beam search。

**Comment by hasky123** [comment]
> 这个式子是等价的，但是他sample用的beam search。
感谢您的回复。意思就是我用nsc，把设置改为：train_sample_method:greedy 、beam_size:5 ？

**Comment by ruotianluo** [comment]
我试过，效果没有sample好

**Comment by hasky123** [comment]
> 我试过，效果没有sample好

另外还有一个问题令我很疑惑，我用普通的scst训练模型，beam=1时的性能：
Bleu_1: 0.806
Bleu_2: 0.652
Bleu_3: 0.510
Bleu_4: 0.392
METEOR: 0.290
ROUGE_L: 0.589
CIDEr: 1.281
当用beam>1，只有：
Bleu_1: 0.806
Bleu_2: 0.653
Bleu_3: 0.510
Bleu_4: 0.392
METEOR: 0.290
ROUGE_L: 0.589
CIDEr: 1.286
beam search对性能几乎没有提升，我很疑惑是什么导致这个现象

**Comment by ruotianluo** [comment]
我也不知道，我不太调beamsizr
