### ISSUE TITLE
请问在做数据预处理时出现error: option --input_json not recognized该如何解决？

### ISSUE THREAD

**Issue by Wangyf1998** [ruotianluo/self-critical.pytorch#264]
您好，当我在使用 python scripts/prepro_feats.py --input_json data/dataset_coco.json --output_dir data/cocotalk --images_root $IMAGE_ROOT 命令对数据进行预处理时报错：
![image](https://user-images.githubusercontent.com/87464929/141815988-1d7a8823-4b07-4b9a-84a4-92b937b9cbe7.png)
此前的python scripts/prepro_labels.py --input_json data/dataset_coco.json --output_json data/cocotalk.json --output_h5 data/cocotalk命令正常运行，请问我是疏忽了哪里么？
感谢！

**Comment by ruotianluo** [comment]
你的$IMAGE_ROOT有值吗

**Comment by Wangyf1998** [comment]
有值，第一次$IMAGE ROOT填写的是train2014和val2014所在文件夹的路径，第二次将train2014和val2014放在/data目录下并写入data目录，两次均会报错

**Comment by ruotianluo** [comment]
我不知道了诶，也太奇怪了。

**Comment by Wangyf1998** [comment]
确实，我再捣鼓一下，挺奇怪的
