### ISSUE TITLE
what I missed ?

### ISSUE THREAD

**Issue by loveJasmine** [ruotianluo/self-critical.pytorch#28]
mldl@mldlUB1604:~/ub16_prj/self-critical.pytorch$ python train.py --id fc --caption_model fc --input_json data/cocotalk.json --input_fc_dir data/cocotalk_fc --input_att_dir data/cocotalk_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log_fc --save_checkpoint_every 6000 --val_images_use 5000 --max_epochs 30
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from misc.rewards import init_cider_scorer, get_self_critical_reward
  File "/home/mldl/ub16_prj/self-critical.pytorch/misc/rewards.py", line 14, in <module>
    from pyciderevalcap.ciderD.ciderD import CiderD
ImportError: No module named pyciderevalcap.ciderD.ciderD

**Comment by ruotianluo** [comment]
You need clone my cider repository. It's in the readme.
