### ISSUE TITLE
pth file missing from resnet

### ISSUE THREAD

**Issue by XinyuHua** [ruotianluo/self-critical.pytorch#3]
Hi Ruotian, this might be a trivial problem but when I try to run this command:

`python scripts/prepro_feats_npy.py`

It reports the following error:

IOError: [Errno 2] No such file or directory: '/home/pytorch-resnet/resnet101.pth'

I've cloned pytorch-resnet from https://github.com/ruotianluo/pytorch-resnet, any idea what I've missed? Thanks in advance!

**Comment by ruotianluo** [comment]
there are links in that repository, just download and replace the path.

**Comment by XinyuHua** [comment]
Thanks! I found it.
