### ISSUE TITLE
evaluation error using pre-trained model

### ISSUE THREAD

**Issue by Wentong-DST** [ruotianluo/self-critical.pytorch#39]
Hi Ruotian,

I tried to run the following script:
``
python eval.py --model resnet50.pth --infos_path infos.pkl --image_folder ./image/val2014_coco/ --num_images 1
``

The model was resnet50 (and resnet101) downloaded from your google drive. But I got the error:
``
Traceback (most recent call last):
  File "eval.py", line 102, in <module>
    model.load_state_dict(torch.load(opt.model))
  File "/home/wentong/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 522, in load_state_dict
    .format(name))
KeyError: 'unexpected key "conv1.weight" in state_dict'
``

I have searched online but there was little information about that. I guess you have used multiple gpus.

Any advice? Thank you for your implementation.

**Comment by Wentong-DST** [comment]
Thank you for your reply.

I can load weights, it is too long, so I just print some:
``
['conv1.weight', 'bn1.weight', 'bn1.bias', 'bn1.running_mean', 'bn1.running_var', 'layer1.0.conv1.weight', 'layer1.0.bn1.weight', 'layer1.0.bn1.bias', ...]
``

The total length of keys is 267. And 'conv1.weight' is there.

But I managed to run evaluation script using "model-best.pth" inside topdown folder.

**Comment by metro-smiles** [comment]
@ruotianluo I was having trouble running the pre-trained model. It gives me a key error when I try to run it.
`self-critical_pytorch/eval_utils.py", line 98, in eval_split
    data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if data['att_masks'] is not None else None]
KeyError: 'att_masks'`
Any possible fixes?

**Comment by ruotianluo** [comment]
Are you using batch size 1?

**Comment by metro-smiles** [comment]
Yes

**Comment by ruotianluo** [comment]
Are you using master branch?

**Comment by metro-smiles** [comment]
Yes. A different batch size of 4 also gives me the same issue

**Comment by ruotianluo** [comment]
are you using dataloader or dataloaderraw?

**Comment by metro-smiles** [comment]
The keys after loading my data are:
`['infos', 'bounds', 'att_feats', 'fc_feats']`

**Comment by metro-smiles** [comment]
Will these still fix the problem of arbitrary images?

**Comment by ruotianluo** [comment]
I mean you could follow these commits and change the ImageCapitoning.pytorch one.
