### ISSUE TITLE
Can you update pretrain model?

### ISSUE THREAD

**Issue by mkseo17** [ruotianluo/self-critical.pytorch#42]
Hello Ruotian, Thank you very much for your work.

I try to experiment with uploded pretrained model(a2i2, topdown).
But there was some errors to both pretrained model with below message

'File "eval.py", line 97, in <module>
    opt.input_box_dir = infos['opt'].input_box_dir
AttributeError: 'Namespace' object has no attribute 'input_box_dir'' 

I guess this error caused by mismatch of infos which was uploaded on 8/8 of last year.
I would appreciate it if you update it :)

**Comment by ruotianluo** [comment]
A simple workaround is to remove that assertion.

**Comment by dhimanpd** [comment]
@mkseo10 Please replace with 96 line in eval_utils with following line.
`        tmp = [data['fc_feats'][np.arange(loader.batch_size) * loader.seq_per_img], 
            data['att_feats'][np.arange(loader.batch_size) * loader.seq_per_img],
            data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if 'att_masks' in data is not None else None]`
The code to check if att_masks is present in data was wrong.
@ruotianluo Can you please fix it in the master branch?

**Comment by ruotianluo** [comment]
I think it shoule be fixed by now?
