### ISSUE TITLE
<EOS> in sampling

### ISSUE THREAD

**Issue by YeDeming** [ruotianluo/self-critical.pytorch#43]
Hi Ruotian,

Thanks for your opening source your code.

As far I'm concerned, line 188 & 189 in models/FCModel.py should be put after line 192.  In appendix of paper self-critical, the author said the < EOS > should be added to calc cider. Maybe the prob of < EOS > also should be updated by gradient. 

Thanks a lot for your time!

Deming Ye

**Comment by ruotianluo** [comment]
nice catch. Thank you very much.
