### ISSUE TITLE
Batch Normalization Error in Bottom Up Model

### ISSUE THREAD

**Issue by HrsPythonix** [ruotianluo/self-critical.pytorch#44]
You implement the batch normalization here:
```
self.att_embed = nn.Sequential(*(
                                ((nn.BatchNorm1d(self.att_feat_size),) if self.use_bn else ())+
                                (nn.Linear(self.att_feat_size, self.rnn_size),
                                nn.ReLU(),
                                nn.Dropout(self.drop_prob_lm))+
                                ((nn.BatchNorm1d(self.rnn_size),) if self.use_bn==2 else ())))
```

And feed it with att_feats, whose size is (batch_size, proposal_num, feature_num(2048)).
Here I assume the proposal_num is fixed, which is 36.
First I got the problem running the batch normalization:
```
RuntimeError: running_mean should contain 36 elements not 2048
```

Then I went to look up the API in Pytorch doc, while I think the batch normalization code should be:
```
nn.BatchNorm1d(self.proposal_num)
```

After changing the code, the training process goes smoothly.

Is this a BUG, or I mistaken the code?

**Comment by ruotianluo** [comment]
The parameter should be the feature size instead of proposal num.

**Comment by HrsPythonix** [comment]
but I got error when I set the parameter as feature size(2048):
`RuntimeError: running_mean should contain 36 elements not 2048
`

**Comment by ruotianluo** [comment]
pack_wrapper should turn the att_feats into Kx2048 it seems that you got something like Xx32xY. Verify if pack_wrapper is feeding Kx2048 into att_embed.

**Comment by HrsPythonix** [comment]
ok I got your idea, thanks for your answer
