### ISSUE TITLE
KeyError in Self-critical training

### ISSUE THREAD

**Issue by WeimianLI** [ruotianluo/self-critical.pytorch#46]
I met a key error in self-critical training. Do you have any idea how to fix it? 

CUDA_VISIBLE_DEVICES=0 python train.py --id bottomup_topdown --caption_model topdown --input_json data/cocotalk.json --input_fc_dir data/cocobu_fc --input_att_dir data/cocobu_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-5 --start_from save-rl/log_bottomup-topdown --checkpoint_path save-rl/log_bottomup-topdown --save_checkpoint_every 6000 --language_eval 1 --val_images_use 5000 --self_critical_after 29

/home/weimian/Downloads/yes/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
tensorboardX is not installed
DataLoader loading json file:  data/cocotalk.json
vocab size is  9487
DataLoader loading h5 file:  data/cocobu_fc data/cocobu_att data/cocotalk_box data/cocotalk_label.h5
max sequence length in data is 16
read 123287 image features
assigned 113287 images to split train
assigned 5000 images to split val
assigned 5000 images to split test
Read data: 0.162038803101
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    train(opt)
  File "train.py", line 128, in train
    reward = get_self_critical_reward(dp_model, fc_feats, att_feats, att_masks, data, gen_result, opt)
  File "/home/weimian/workplace/project/self-critical.pytorch/misc/rewards.py", line 62, in get_self_critical_reward
    _, cider_scores = CiderD_scorer.compute_score(gts, res_)
  File "cider/pyciderevalcap/ciderD/ciderD.py", line 48, in compute_score
    (score, scores) = cider_scorer.compute_score(self._df)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 199, in compute_score
    score = self.compute_cider(df_mode)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 173, in compute_cider
    vec, norm, length = counts2vec(test)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 122, in counts2vec
    df = np.log(max(1.0, self.document_frequency[ngram]))
KeyError: ('290', '1042')
Terminating BlobFetcher

**Comment by ruotianluo** [comment]
Are you using this https://github.com/ruotianluo/cider.git? If you are, can you try rerun the prepro_ngrams?

**Comment by WeimianLI** [comment]
I replace the cider with the one you provided and the self-critical training starts. Thanks for you help!

**Comment by misogil0116** [comment]
Hi, same problem occurred to me, and something has wrong even though I download cider from  https://github.com/ruotianluo/cider.git .
I tried `CUDA_VISIBLE_DEVICES =0 python train.py ..`, and this setting solved my problem.
