### ISSUE TITLE
ValueError: result of slicing is an empty tensor

### ISSUE THREAD

**Issue by WERush** [ruotianluo/self-critical.pytorch#5]
Hi, ruotian,

When I run the training command, 
'$ python train.py --id fc --caption_model fc --input_json data/cocotalk.json --input_fc_dir data/cocotalk_fc --input_att_dir data/cocotalk_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log_fc --save_checkpoint_every 6000 --val_images_use 5000 --max_epochs 30', 

I encountered the error '"ValueError: result of slicing is an empty tensor"', and the error info was located in this [line](https://github.com/ruotianluo/self-critical.pytorch/blob/master/models/FCModel.py#L29) . 
I find that the size of 'sigmoid_chunk' is (50L, 50L, 2560L) with batch_size=10. I  baffle how the 'narrow' method is applied on the 'sigmoid_chunk'. 
Can you explain this line (https://github.com/ruotianluo/self-critical.pytorch/blob/master/models/FCModel.py#L29) ?

**Comment by ruotianluo** [comment]
sigmoid_chunk should be (50L, 2560L)  (batch_size 10 , seq_per_img 5, that's why 50).

**Comment by WERush** [comment]
I run the command 'sigmoid_chunk.size()' and it shows (50L,50L,2560); I find other captionmodels, such as att2in and att2in2, work well.

**Comment by ruotianluo** [comment]
What's the size of xt.

**Comment by WERush** [comment]
(50L, 512L)

**Comment by WERush** [comment]
I suppose it is the state[0][-1]. I find the size of state[0][-1] is (50L, 1L, 512L). The broadcasting of pytorch-0.2 makes the result become (50L, 50L, 512L)

**Comment by ruotianluo** [comment]
I'm using 0.2, but it doesn't occur to me.
Can you print the timestep.
and print the size of states at every time step.

The initial states should both be (1, 50, 512), so it's really wierd.

**Comment by WERush** [comment]
I add the torch.squeeze() in front of xt and state[0][-1]. The model works well and no error happens.

**Comment by ruotianluo** [comment]
Just feel like there maybe some bug in my code or in your pytorch build.

**Comment by WERush** [comment]
Only the FCmodel has such error. BTW, the version of my pytorch is 0.2.0_2

**Comment by ruotianluo** [comment]
I found the problem.

**Comment by WERush** [comment]
Where is the problem? BTW, I friend you on WeChat. :)

**Comment by ruotianluo** [comment]
Pushed to master already.
