### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ivy94419** [ruotianluo/self-critical.pytorch#52]
I have trained a model without self-critical, and run eval.py， an error occurs:

```
File "/host/xx/self-critical/eval_utils.py", line 143, in eval_split
    lang_stats = language_eval(dataset, predictions, eval_kwargs['id'], split)
  File "/host/xx/self-critical/eval_utils.py", line 39, in language_eval
    cocoRes = coco.loadRes(cache_path)
  File "/usr/local/lib/python3.5/dist-packages/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
```

How should I do?

**Comment by ivy94419** [comment]
I use default parameters batch_size=0

I found something stange, when evalating, the image_id is not correct, it is start from 0 to num_images:
![image](https://user-images.githubusercontent.com/4054390/43998893-61118376-9e33-11e8-9880-87b2dd80b260.png)

so it can find cooresponding index from 'captions_val2014.json'

but I don't know why the index is wrong, and how to solve it

**Comment by ivy94419** [comment]
I have fixed this problem by change 

`entry = {'image_id': data['infos'][k]['id'], 'caption': sent}`
 
to

`entry = {'image_id': int(data['infos'][k]['file_path'].split('_')[-1].split('.')[0]), 'caption': sent}`  in **_eval_utils.py_**

**Comment by ivy94419** [comment]
@ruotianluo I trained self-critical model using default parameters, and an error occurs:

> data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if data['att_masks'] is not None else None]
> KeyError: 'att_masks'
> 
I followed the latest comment in [#42](https://github.com/ruotianluo/self-critical.pytorch/issues/42) to change 96 line in eval_utils, but other problem occurs:

>     data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if 'att_masks' in data is not None else None]
> TypeError: 'NoneType' object is not subscriptable

How should I do ?  Thank you very much

**Comment by ivy94419** [comment]
I think I can both train and eval the model now.
This is for training:
` 
data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if data['att_masks'] is not None else None]
 `

This is for evaluating:
`data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if 'att_masks' in data is not None else None]`

**Comment by AlanGCheng** [comment]
> I have fixed this problem by change
> 
> `entry = {'image_id': data['infos'][k]['id'], 'caption': sent}`
> 
> to
> 
> `entry = {'image_id': int(data['infos'][k]['file_path'].split('_')[-1].split('.')[0]), 'caption': sent}` in **_eval_utils.py_**

thank you very much ! this help me solve the same problem in repo ruotianluo/ImageCaptioning.pytorch
