### ISSUE TITLE
About multi-GPU training

### ISSUE THREAD

**Issue by xuyan1115** [ruotianluo/self-critical.pytorch#53]
hi~,
when I tried to train the fc_model on 2 GPUs by setting the environment variable `CUDA_VISIBLE_DEVICES=0,1`,  I ran this code with some errors in[ train.py#125](https://github.com/ruotianluo/self-critical.pytorch/blob/510b0e02d1fcf43a5281bebb147ca1bce5db45f1/train.py#L125), but there were no errors when I ran your codes with only one GPU.

Does this repository support multi-GPUs training?

**Comment by xuyan1115** [comment]
This is the error:

Traceback (most recent call last):
  File "train.py", line 224, in <module>
    train(opt)
  File "train.py", line 125, in train
    loss = crit(dp_model(fc_feats, att_feats, labels, att_masks), labels[:,1:], masks[:,1:])
  File "/usr/lib64/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 124, in forward
    return self.gather(outputs, self.output_device)
  File "/usr/lib64/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 136, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/lib64/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 67, in gather
    return gather_map(outputs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/parallel/scatter_gather.py", line 54, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/usr/lib64/python2.7/site-packages/torch/nn/parallel/_functions.py", line 65, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/usr/lib64/python2.7/site-packages/torch/cuda/comm.py", line 160, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Gather got an input of invalid size: got [25, 15, 9488], but expected [25, 17, 9488] (gather at torch/csrc/cuda/comm.cpp:183)
frame #0: <unknown function> + 0xc4f7fa (0x7fe137f137fa in /usr/lib64/python2.7/site-packages/torch/_C.so)
frame #1: <unknown function> + 0x3913db (0x7fe1376553db in /usr/lib64/python2.7/site-packages/torch/_C.so)
<omitting python frames>
frame #9: THPFunction_apply(_object*, _object*) + 0x38f (0x7fe137a34c8f in /usr/lib64/python2.7/site-packages/torch/_C.so)
frame #36: __libc_start_main + 0xf5 (0x7fe1cd78bc05 in /lib64/libc.so.6)
frame #37: python() [0x400721]

**Comment by KaiKangSDU** [comment]
Do you have any suggestion to deal with this error?

**Comment by ruotianluo** [comment]
Do you know where 9488 comes from?

**Comment by xuyan1115** [comment]
@KaiKangSDU 
I don't solve this error, but I roughly know the reason of the error.

In `_forward` function, we run `seq.size(1) - 1` iterations to generated captions, but in every iteration, we judge `seq[:, i].sum() == 0`, which caused different length of captions for different images, so they cannot gather together.

Maybe you can remove this condition to fix this error, I don't try it because I only need a checkpoint to do other things.

**Comment by xuyan1115** [comment]
@ruotianluo 
vocab size + 1 = 9488

**Comment by ruotianluo** [comment]
Yes. These are relatively deprecated models. Try models in AttModel.py

**Comment by KaiKangSDU** [comment]
@xuyan1115 
Thanks.
When I ran the raw code, I don't encounter this error. Comparison with my modified code, I found I add wrong allocating GPU code, which may result in conflict. When I remove it, the program works. I am not sure whether the error is related to the code of allocating GPU.

**Comment by xuyan1115** [comment]
@ruotianluo 
My task is based on "show attend and tell" model, so I have to modify OldModel.py.

I'm confused that what's the different between AttModel.py (Att2in, Att2all) and OldModel.py (ShowAttendTell)?

**Comment by ruotianluo** [comment]
Att2in2 is a better attention based model proposed in self critical paper.

**Comment by xuyan1115** [comment]
@KaiKangSDU @ruotianluo 
Thanks for your answers, I have solved this problem.

**Comment by KaiKangSDU** [comment]
@xuyan1115
How do you solve this problem?Thanks in advance:smile:

**Comment by KaiKangSDU** [comment]
@xuyan1115 how do you solve this problem?:smile:
Thanks

**Comment by KaiKangSDU** [comment]
@xuyan1115 
I see... I will check it later. Thanks for your replying.:smiley:
