### ISSUE TITLE
when preprocess the test features of BottomUp , the image with the id=321486, has some bugs

### ISSUE THREAD

**Issue by wzn0828** [ruotianluo/self-critical.pytorch#54]
When I preprocess the MSCOCO test2014 BottomUp features, a bug happened with the image 321486
![image](https://user-images.githubusercontent.com/29533484/44616392-698e9680-a881-11e8-9de4-75d02e42292e.png)

Could you help me with something?

**Comment by beckhamchen** [comment]
just ignore it, use try..except. Acturally, 3 items are incorrect. But doesn't matter, all features will be correctly generated.

**Comment by wzn0828** [comment]
@beckhamchen Thank you very much, I got it.
