### ISSUE TITLE
ImportError: No module named misc.resnet_utils (while running the prepro_feats.py)

### ISSUE THREAD

**Issue by mauricioarmani** [ruotianluo/self-critical.pytorch#56]
I had this issue trying to run scripts/prepro_feats.py. Looks like the script could not import the above module misc.

Worked for me changing the prepro_feats.py on lines 49 and 50 to:

```
from ..misc.resnet_utils import myResnet
import ..misc.resnet as resnet
```

and running (from the above repo's path):

`python -m self_critical.scripts.prepro_feats --input_json self_critical/data/dataset_coco.json --output_dir self_critical/data/cocotalk --images_root $IMAGE_ROOT --model_root self_critical/data/imagenet_weights/`

Notice that I changed the repo's name to avoid conflict (Not sure if it's necessary).

**Comment by nwpuhq** [comment]
My terminal 's path is '~/下载/ImageCaptioning$ ',and when i run the command:python2 scripts/prepro_feats.py --input_json data/dataset_coco.json --output_dir data/cocotalk --images_root $IMAGE_ROOT，i get an error:
Traceback (most recent call last):
  File "scripts/prepro_feats.py", line 43, in <module>
    from misc.resnet_utils import myResnet
ImportError: No module named misc.resnet_utils
how i can solve it?Thansk

**Comment by ZishunYu** [comment]
changing lines 49 and 50
from ..misc.resnet_utils import myResnet
form ..misc import resnet
works for me

Indeed I think changing repo's name is necessary for me, I have to get rid of '.' in the repo's name to make it work.
I also run it from above the repo's path, didn't try running from repo's root path

**Comment by chillum1718** [comment]
> I had this issue trying to run scripts/prepro_feats.py. Looks like the script could not import the above module misc.
> 
> Worked for me changing the prepro_feats.py on lines 49 and 50 to:
> 
> ```
> from ..misc.resnet_utils import myResnet
> import ..misc.resnet as resnet
> ```
> 
> and running (from the above repo's path):
> 
> `python -m self_critical.scripts.prepro_feats --input_json self_critical/data/dataset_coco.json --output_dir self_critical/data/cocotalk --images_root $IMAGE_ROOT --model_root self_critical/data/imagenet_weights/`
> 
> Notice that I changed the repo's name to avoid conflict (Not sure if it's necessary).

have you solve this...... because iam also facing the same problem

**Comment by ruotianluo** [comment]
Do you still have the problem with the master branch?
