### ISSUE TITLE
KeyError when evaluating model-best

### ISSUE THREAD

**Issue by zhengyi123456** [ruotianluo/self-critical.pytorch#60]
Here is the log information:
-----------------------------------------
zy@zyj011-desktop:~/critical$ python eval.py --model ./log_fc_rl/model-best.pth --infos                                                                                                                        _path ./log_fc_rl/infos_fc_rl-best.pkl --image_folder ./image --num_images 10
DataLoaderRaw loading images from folder:  ./image
0
listing all images in directory ./image
DataLoaderRaw found  12  images
Traceback (most recent call last):
  File "eval.py", line 137, in <module>
    vars(opt))
  File "/home/zy/critical/eval_utils.py", line 99, in eval_split
    data['att_masks'][np.arange(loader.batch_size) * loader.seq_per_img] if data['att_masks'] is not None else None]
KeyError: 'att_masks'
---------------------------------------------
I used FC model with self-critical

**Comment by ruotianluo** [comment]
This model doesn't support arbitrary images.

**Comment by ruotianluo** [comment]
In fact it may support arbitray images. I just am never putting effort on it anymore.

**Comment by ruotianluo** [comment]
You can have a try.
