### ISSUE TITLE
Bottom up Test2014 features not extracting with make bu data

### ISSUE THREAD

**Issue by ankit1khare** [ruotianluo/self-critical.pytorch#63]
I tried creating numpy files from test2014 variable box features from P.Anderson's git using make_bu_data. but there's an error in padding while decoding from string to numpy array.

 item[field] = np.frombuffer(base64.decodestring(item[field]), 
                        dtype=np.float32).reshape((item['num_boxes'],-1))

it says, incorrect padding within decodestring function. I tried adding ''=" at the end but then the dimensions of resultant numpy array mismatches with num_boxes. This error occurs for every tsv file in test2014 adaptive feature set. 
Any help would be appreciated.

**Comment by lukemelas** [comment]
How about something like this for `make_bu_data.py`: 

```
def decode_base64(data):
    """Decode base64, padding being optional.
    :param data: Base64 data as an ASCII byte string
    :returns: The decoded byte string.
    """
    missing_padding = len(data) % 4
    if missing_padding != 0:
        data += b'='* (4 - missing_padding)
    return base64.decodestring(data)


for infile in infiles:
    print('Reading ' + infile)
    with open(os.path.join(args.downloaded_feats, infile), "r+b") as tsv_in_file:
        reader = csv.DictReader(tsv_in_file, delimiter='\t', fieldnames = FIELDNAMES)
        for item in reader:
            item['image_id'] = int(item['image_id'])
            item['num_boxes'] = int(item['num_boxes'])
    
            if len(item['features']) % 4 != 0 or len(item['boxes']) % 4 != 0:
                continue
                # print(item['image_id'])
                #pdb.set_trace()
            
            for field in ['boxes', 'features']:
                item[field] = np.frombuffer( decode_base64(item[field]), 
                        dtype=np.float32).reshape((item['num_boxes'],-1))
            np.savez_compressed(os.path.join(args.output_dir+'_att', str(item['image_id'])), feat=item['features'])
            np.save(os.path.join(args.output_dir+'_fc', str(item['image_id'])), item['features'].mean(0))
            np.save(os.path.join(args.output_dir+'_box', str(item['image_id'])), item['boxes'])

print('Done.')
```

Let me know how that works.

**Comment by ankit1khare** [comment]
trying.....

**Comment by ankit1khare** [comment]
That seems to work. The folders has right number of files. I just need to write the code for using those features and checking how they contribute towards evaluation on the server. 
I'm very thankful for quick response and elegant solution.

**Comment by lukemelas** [comment]
Great. Happy to help!

**Comment by gorgeousyouth** [comment]
> Great. Happy to help!



> That seems to work. The folders has right number of files. I just need to write the code for using those features and checking how they contribute towards evaluation on the server.
> I'm very thankful for quick response and elegant solution.
i have encounter the problem: ValueError: buffer size must be a multiple of element size
