### ISSUE TITLE
Understanding the difference between Att2in2 and Att2in models

### ISSUE THREAD

**Issue by se4u** [ruotianluo/self-critical.pytorch#7]
Hi,

I noticed in your `Readme` that you mentioned that with the `Att2in` model it was not possible for you to reproduce the `SCTS` results, but you were able to get 112 Cider reported in `SCTS` by using `Att2in2` model. I am trying to understand what changes you had to make to reproduce the `SCTS` results, but as far I could see by reading the code in `AttModel.py` and `Att2InModel.py` both the models are actually doing the same thing. Apart from the fact that the mode in `AttModel.py` is more modular and beautifully refactored/organized the actual computation seems to be the same as the original model. I also tried to look at the commit logs to get some idea but I couldn't really see any specific model related bugfixes. Could you say what was the error before and how you debugged/fixed it?

Thanks.

**Comment by ruotianluo** [comment]
I actually forgot how att2in can achieve now, it shouldn't be too bad I guess. The main different between att2in is the embedding layers;(att_embed and word embedding). A two-layer MLP embedding will boost performance quite a lot.
