### ISSUE TITLE
Cider-D computation cofusion

### ISSUE THREAD

**Issue by congve1** [ruotianluo/self-critical.pytorch#71]
Hi, @ruotianluo . I'm little confused about  your code about computing cider-D score. I'm wondering why you choose to compute the n-grams using all the captions of the coco-dataset instead of using the reference captions to compute the n-grams.

**Comment by ruotianluo** [comment]
It's how it's done during test time. The intuition is that the tf-idf is measured from the whole corpus.

**Comment by congve1** [comment]
thank you. This means to make the cider score more stable. Am I right?
