### ISSUE TITLE
训练最开始reward接近于0的问题

### ISSUE THREAD

**Issue by gohsyi** [ruotianluo/self-critical.pytorch#72]
您好，我是nlp的初学者，有个问题想请教

在训练最开始的时候生成的caption与gt差距非常大，reward会接近于0，这时候算loss也会非常小，网络更新会不会很慢？

**Comment by ruotianluo** [comment]
事实上不会那么接近0。更新肯定是会慢一点，还可以吧。topdown bottomup里面有他们用的更快的方法。
