### ISSUE TITLE
Is 'Evaluate on raw images' not supported yet?

### ISSUE THREAD

**Issue by YuansongFeng** [ruotianluo/self-critical.pytorch#73]
Thanks very much for the awesome repo @ruotianluo . 

Is the section _Evaluate on raw images_ not supported yet? Based on my understanding, this section requires the use of dataloaderraw.py, which does not have data['att_mask'] properly set yet. Or am I understanding something wrong? 

All I am trying to do is generating caption for **some** images. Any pointer is appreciated!

**Comment by ruotianluo** [comment]
It's fixed now.
