### ISSUE TITLE
After Start training, I got a problem about no such file  'log_fc/model.pth' 

### ISSUE THREAD

**Issue by pandadreamer** [ruotianluo/self-critical.pytorch#82]
Like this: 
![image](https://user-images.githubusercontent.com/38282854/56094167-945a5780-5f03-11e9-8316-5d56f07b1e32.png)

Anyone know this?

Thank you~

**Comment by congve1** [comment]
maybe the directory `log_fc` does not exist, you should create the directory first.

**Comment by pandadreamer** [comment]
@congve1 Thank u !!!
I create a empty dict so it run
