### ISSUE TITLE
error: it should be use_att, use_fc = True, True

### ISSUE THREAD

**Issue by xuxuzhou** [ruotianluo/self-critical.pytorch#87]
https://github.com/ruotianluo/self-critical.pytorch/blob/20c0df783aa8d7616e1506c31a5b68f12226d5cf/misc/utils.py#L51

**Comment by ruotianluo** [comment]
Because you are using top-down?

**Comment by xuxuzhou** [comment]
> Because you are using top-down?

Yes, topdown is not in ['show_tell', 'all_img', 'fc', 'newfc'] and 'languagemodel', but it has no input for fc features.
I didn't know much about other models, but for topdown model, it should be set according to the title?

**Comment by ruotianluo** [comment]
you are right.

**Comment by ruotianluo** [comment]
fixed.
