### ISSUE TITLE
TypeError: pickle_dump() got an unexpected keyword argument 'protocol'

### ISSUE THREAD

**Issue by haiboowang** [ruotianluo/self-critical.pytorch#88]
当我在使用强化学习方法训练时的第一步处理数据和计算cider指标得分时出现错，无法解决，请帮助我！
when i train using self critical, preprocess the dataset and get the cache for calculating cider score,got an error, please help me ！

python scripts/prepro_ngrams.py --input_json data/dataset_coco.json --dict_json data/cocotalk.json --output_pkl data/coco-train --split train
('total imgs:', 113287)
Traceback (most recent call last):
  File "scripts/prepro_ngrams.py", line 136, in <module>
    main(params)
  File "scripts/prepro_ngrams.py", line 121, in main
    utils.pickle_dump({'document_frequency': ngram_words, 'ref_len': ref_len}, open(params['output_pkl']+'-words.p','w'), protocol=cPickle.HIGHEST_PROTOCOL)
TypeError: pickle_dump() got an unexpected keyword argument 'protocol

**Comment by ruotianluo** [comment]
我忘了push commit了。你把那个protocal=之后的删掉

**Comment by haiboowang** [comment]
> 我忘了push commit了。你把那个protocal=之后的删掉

问题解决了，非常感谢！

**Comment by Jordan-5i** [comment]
我在运行prepro_ngrams.py时出现了一下错误，我用的是python3.6.7，这个问题是出在哪里？
File "F:/PyTorchProjects/self-critical.pytorch-master/scripts/prepro_ngrams.py", line 150, in <module>
    main(params)
  File "F:/PyTorchProjects/self-critical.pytorch-master/scripts/prepro_ngrams.py", line 135, in main
    utils.pickle_dump({'document_frequency': ngram_words, 'ref_len': ref_len}, open(params['output_pkl']+'-words.p','w'))
  File "F:\PyTorchProjects\self-critical.pytorch-master\misc\utils.py", line 38, in pickle_dump
    return cPickle.dump(obj, f, protocol=2)
TypeError: write() argument must be str, not bytes

还有一个问题，
https://github.com/ruotianluo/self-critical.pytorch/blob/9b36d9bf1cad47cd8c917c895d926b3ff3d3e5e8/scripts/prepro_ngrams.py#L120
在这里的‘bpe’是什么意思，有什么作用？

**Comment by Jordan-5i** [comment]
@ruotianluo

**Comment by ruotianluo** [comment]
因为python2和python3的语法问题吧。

BPE是Byte pair encoding，language里面常用

**Comment by Jordan-5i** [comment]
那我应该怎么去修改呢？麻烦你指点一下，非常感谢。

**Comment by ruotianluo** [comment]
我这两天比较忙，你能先自己百度一下吗，pickle python2 python3什么的

**Comment by ruotianluo** [comment]
utils.pickle_dump({'document_frequency': ngram_words, 'ref_len': ref_len}, open(params['output_pkl']+'-words.p','wb'))
should work
