### ISSUE TITLE
About tensorflow version

### ISSUE THREAD

**Issue by watsonyanghx** [ruotianluo/self-critical.pytorch#9]
Hi, thanks for your generosity to share this great repository.

Since I have been using tensorflow all the time and know little about pytorch, I'm trying to read the code but find it hard for me to understand. I'm curious about whether there will be tensorflow version of this repository?

Thanks.

**Comment by ruotianluo** [comment]
You can search by google, I remember there is one tensorflow implementation. 

Ruotian Luo

**Comment by watsonyanghx** [comment]
OK, I will do it. Thank you!
