### ISSUE TITLE
prepro_ngrams in ciderD

### ISSUE THREAD

**Issue by zhengyi123456** [ruotianluo/self-critical.pytorch#90]
你好，请问在计算ciderD之前需要运行prepro_ngrams对数据进行一次预处理的工作，将token转换为字典ID，请问在真实计算cider的过程使使用这个ID进行计算吗？ 因此是否不允许多个字典的存在，即相同的ID在不同的字典内表示不同的词。

**Comment by ruotianluo** [comment]
1 真实是指什么？没懂。 2 你可以initialize多个scorer，就可以多个字典了。
