### ISSUE TITLE
preformance on other dataset

### ISSUE THREAD

**Issue by xuxuzhou** [ruotianluo/self-critical.pytorch#92]
Hi, I use the flickr30k dataset, but got very bad performance.
What I have changed is the input_json, input_fc_dir, input_att_dir, input_label_h5, and the files are produced followed by your method in readme. 
What else should I do or something else is missed?

**Comment by pandadreamer** [comment]
You said change input_fc_dir, input_att_dir.
Are you sure you have generated the att_feats and fc_feats using bottom-up or just resnet in flickr30k dataset?

**Comment by xuxuzhou** [comment]
> You said change input_fc_dir, input_att_dir.
> Are you sure you have generated the att_feats and fc_feats using bottom-up or just resnet in flickr30k dataset?

Yes, the json file and feature all produced with flickr30k. I have found a problem, I still use the coco file as annFile, so I get the wrong score in test. 
I need to check the pipeline is right.

**Comment by chengxili** [comment]
Hi, how to get f30ktalk_fc(fc_feats) using the method in the readme. Seems I can only get cocotalk_fc. Any help?

**Comment by chengxili** [comment]
Hi, how to get f30kbu_fc(fc_feats) using the method in the readme. Seems I can only get cocotalk_fc or f30kbu_att.pth . Any help?

**Comment by ruotianluo** [comment]
A simple way is you manually average each att feature and get a 2048x1 vector.
