### ISSUE TITLE
evaluation error using pre-trained model

### ISSUE THREAD

**Issue by I-NI** [ruotianluo/self-critical.pytorch#96]
when I try to run the following script:
python eval.py --model model-best.pth --infos_path infos_a2i2-best.pkl --image_folder blah --num_images 15
I meet this error:
DataLoaderRaw loading images from folder:  blah
0
listing all images in directory blah
DataLoaderRaw found  13  images
Traceback (most recent call last):
  File "eval.py", line 144, in <module>
    vars(opt))
  File "/media/sdb/Chen/deeplearning/LSTM/self/eval_utils.py", line 113, in eval_split
    tmp = [_.cuda() if _ is not None else _ for _ in tmp]
AttributeError: 'numpy.ndarray' object has no attribute 'cuda'

Thanks for any advice!

**Comment by ruotianluo** [comment]
https://github.com/ruotianluo/self-critical.pytorch/blob/master/dataloader.py#L226

Add this to the end of get_batch in dataloader_raw.py

**Comment by I-NI** [comment]
it works! Thank you!

**Comment by hishamabutt** [comment]
@I-NI can you share the changes you have made in dataloaderraw.py?
