### ISSUE TITLE
Really bad quality of captions throughout the whole training. Help needed.

### ISSUE THREAD

**Issue by hecoding** [ruotianluo/self-critical.pytorch#98]
Hi @ruotianluo, thanks for your implementation.

I'm having some problems replicating the results, maybe you could give a quick hand.

During the in-train validation descriptions can be seen. The models seems to output only the tokens it's most confident about.
```
image 184613: at person UNK black some out other the the the
image 403013: at person UNK black some the the the the the
image 562150: at person UNK black cat the the the the the
image 360772: at person UNK black some the the the toilet
image 340559: at person UNK black some the the the the the
image 321107: at person UNK black some the the the the
image 129001: at person UNK black some the the the toilet
image 556616: at person UNK black some the the the the
image 472621: at person UNK black some the the the the toilet
image 364521: at person UNK black some out the the the the
evaluating validation preformance... 9/5000 (30.373465)
```
The output above is from epoch ~46. Below is what appears right before the evaluation. One can see it was almost at 600k iterations.
```
Read data: 0.04527854919433594
Cider scores: 0.32052843945697246
iter 527997 (epoch 46), avg_reward = 0.001, time/batch = 0.245
Read data: 0.03418421745300293
Cider scores: 0.20365132843559203
iter 527998 (epoch 46), avg_reward = -0.001, time/batch = 0.258
Read data: 0.045682668685913086
Cider scores: 0.1074919187224149
iter 527999 (epoch 46), avg_reward = -0.000, time/batch = 0.256
```
However it seems to be happening through all the epochs.

What I did was to download the FC model from the Drive folder (`neuraltalk2/no_finetune/FC/`) and the precomputed botom-up features. Then started the sc training with the default
```
$ python train.py --id fc_rl --caption_model fc --input_json data/cocotalk.json --input_fc_dir data/cocobu_fc --input_att_dir data/cocobu_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-5 --start_from log_fc_rl --checkpoint_path log_fc_rl --save_checkpoint_every 6000 --language_eval 1 --val_images_use 5000 --self_critical_after 30
```

These are the scores of the most recent evaluation (epoch 45 I think)
```
{'testlen': 47325, 'reflen': 46783, 'guess': [47325, 42325, 37325, 32325], 'correct': [9115, 115, 0, 0]}
ratio: 1.0115854049547697
Bleu_1: 0.193
Bleu_2: 0.023
Bleu_3: 0.000
Bleu_4: 0.000
computing METEOR score...
METEOR: 0.052
computing Rouge score...
ROUGE_L: 0.133
computing CIDEr score...
CIDEr: 0.059
computing SPICE score...
SPICE: 0.018
computing WMD score...
WMD: 0.064
model saved to log_fc_rl/model.pth
model saved to log_fc_rl/model-528000.pth
```

My point is that all scores seems to be going up correctly and consistently, but the quality of the captions is disastrous. Am I doing something wrong?

This is exactly what happened to my own implementation also, so I came to reproduce these good results.

Any kind of help is greatly appreciated.

**Comment by ruotianluo** [comment]
This first 

python train.py --id fc --caption_model fc --input_json data/cocotalk.json --input_fc_dir data/cocotalk_fc --input_att_dir data/cocotalk_att --input_label_h5 data/cocotalk_label.h5 --batch_size 10 --learning_rate 5e-4 --learning_rate_decay_start 0 --scheduled_sampling_start 0 --checkpoint_path log_fc --save_checkpoint_every 6000 --val_images_use 5000 --max_epochs 30

**Comment by gorgeousyouth** [comment]
请问一下，直接把这两个一步完成有什么区别？就是第二次不加载预训练模型，直接从30之后使用Cider-d优化。分为两步的区别是什么呢？

**Comment by zzy-ucas** [comment]
Hi @hecoding, I meet the same problem when I try to modify the code for finetuning the encoder and decoder simultaneously. But I have no idea why this happened. No matter which model I choose to run the code, the results are the same. Have you solved this problem? Hope to hear from you not soon.

**Comment by hecoding** [comment]
Hi @zzy-ucas. No, I moved on unfortunately...
One thing you can try is to train the XE model yourself instead of using the pretrained ones, as Ruotian suggested. Iirc, it gave better results this way, before I stopped working on this.
Let us now to close the issue. good luck!

**Comment by zzy-ucas** [comment]
Thx @hecoding, I have sovled my problem. How stupid of me! The training progress is okay but I forgot to modify the `annFile` path(captions_val2014.json) for evaluating. FYI, my work is to train models for remote sensing image captioning. So there are a lots of things I have to do for runing the code with remote sensing data. 

Whatever, THX bro!

**Comment by hecoding** [comment]
@zzy-ucas haha nice. yeah shit always happens.
Cool stuff man! glad it got solved.

no problem, cheers.
